/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 7 "tr.c"
typedef long long __int64_t;
#line 18 "tr.c"
typedef unsigned long __darwin_size_t;
#line 54 "tr.c"
typedef __int64_t __darwin_off_t;
#line 85 "tr.c"
typedef __darwin_size_t size_t;
#line 86 "tr.c"
typedef __darwin_off_t fpos_t;
#line 87 "tr.c"
struct __sbuf {
   unsigned char *_base ;
   int _size ;
};
#line 91
struct __sFILEX;
#line 91
struct __sFILEX;
#line 92 "tr.c"
struct __sFILE {
   unsigned char *_p ;
   int _r ;
   int _w ;
   short _flags ;
   short _file ;
   struct __sbuf _bf ;
   int _lbfsize ;
   void *_cookie ;
   int (*_close)(void * ) ;
   int (*_read)(void * , char * , int  ) ;
   fpos_t (*_seek)(void * , fpos_t  , int  ) ;
   int (*_write)(void * , char const   * , int  ) ;
   struct __sbuf _ub ;
   struct __sFILEX *_extra ;
   int _ur ;
   unsigned char _ubuf[3] ;
   unsigned char _nbuf[1] ;
   struct __sbuf _lb ;
   int _blksize ;
   fpos_t _offset ;
};
#line 92 "tr.c"
typedef struct __sFILE FILE;
#line 1064 "tr.c"
struct Address {
   int id ;
   int set ;
   char name[512] ;
   char email[512] ;
};
#line 1070 "tr.c"
struct Database {
   struct Address rows[100] ;
};
#line 1073 "tr.c"
struct Connection {
   FILE *file ;
   struct Database *db ;
};
/* compiler builtin: 
   char *__builtin___strncpy_chk(char * , char const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   long __builtin_expect(long  , long  ) ;  */
/* compiler builtin: 
   unsigned long __builtin_object_size(void * , int  ) ;  */
#line 121
extern int fclose(FILE * ) ;
#line 124
extern int fflush(FILE * ) ;
#line 128
extern FILE *fopen(char const   * , char const   * )  __asm__("_fopen")  ;
#line 132
extern size_t fread(void * , size_t  , size_t  , FILE * ) ;
#line 139
extern size_t fwrite(void const   * , size_t  , size_t  , FILE * )  __asm__("_fwrite")  ;
#line 143
extern void perror(char const   * ) ;
#line 144
extern int ( /* format attribute */  printf)(char const   *  , ...) ;
#line 150
extern void rewind(FILE * ) ;
#line 176
extern int __swbuf(int  , FILE * ) ;
#line 178 "tr.c"
__inline extern int ( __attribute__((__always_inline__)) __sputc)(int _c , FILE *_p ) 
{ 
  unsigned char *tmp ;
  unsigned char tmp___0 ;
  int tmp___1 ;

  {
#line 179
  (_p->_w) --;
#line 179
  if (_p->_w >= 0) {
#line 180
    tmp = _p->_p;
#line 180
    (_p->_p) ++;
#line 180
    tmp___0 = (unsigned char )_c;
#line 180
    *tmp = tmp___0;
#line 180
    return ((int )tmp___0);
  } else
#line 179
  if (_p->_w >= _p->_lbfsize) {
#line 179
    if ((int )((char )_c) != 10) {
#line 180
      tmp = _p->_p;
#line 180
      (_p->_p) ++;
#line 180
      tmp___0 = (unsigned char )_c;
#line 180
      *tmp = tmp___0;
#line 180
      return ((int )tmp___0);
    } else {
#line 182
      tmp___1 = __swbuf(_c, _p);
#line 182
      return (tmp___1);
    }
  } else {
#line 182
    tmp___1 = __swbuf(_c, _p);
#line 182
    return (tmp___1);
  }
}
}
#line 243
extern  __attribute__((__noreturn__)) void __assert_rtn(char const   * , char const   * , int  , char const   * ) ;
#line 847
extern int atoi(char const   * ) ;
#line 855
extern  __attribute__((__noreturn__)) void exit(int  ) ;
#line 856
extern void free(void * ) ;
#line 863
extern void *malloc(size_t  ) ;
#line 985
extern int *__error(void) ;
#line 1063 "tr.c"
int Num  =    2;
#line 1077 "tr.c"
void die(char const   *message ) 
{ 
  int *tmp ;

  {
#line 1079
  tmp = __error();
#line 1079
  if (*tmp) {
#line 1080
    perror(message);
  } else {
#line 1082
    printf("ERROR: %s\n", message);
  }
#line 1084
  exit(1);
}
}
#line 1086 "tr.c"
void Address_print(struct Address *addr ) 
{ 


  {
#line 1088
  printf("%d %s %s\n", addr->id, addr->name, addr->email);
#line 1090
  return;
}
}
#line 1091 "tr.c"
void Database_load(struct Connection *conn ) 
{ 
  int rc ;
  int tmp ;

  {
#line 1093
  tmp = (int )fread((void *)conn->db, sizeof(struct Database ), (size_t )1, conn->file);
#line 1093
  rc = tmp;
#line 1094
  if (rc != 1) {
#line 1094
    die("Failed to load database.");
  }
#line 1095
  return;
}
}
#line 1096 "tr.c"
struct Connection *Database_open(char const   *filename , char mode ) 
{ 
  struct Connection *conn ;
  struct Connection *tmp ;
  long tmp___0 ;
  long tmp___1 ;

  {
#line 1098
  tmp = (struct Connection *)malloc(sizeof(struct Connection ));
#line 1098
  conn = tmp;
#line 1099
  Num --;
#line 1100
  tmp___0 = __builtin_expect((long )(! (Num >= 0)), 0L);
#line 1100
  if (tmp___0) {
#line 1100
    __assert_rtn("Database_open", "test/database.c", 57, "Num >=0");
  }
#line 1101
  if (! conn) {
#line 1101
    die("Memory error");
  }
#line 1102
  conn->db = (struct Database *)malloc(sizeof(struct Database ));
#line 1103
  Num --;
#line 1104
  tmp___1 = __builtin_expect((long )(! (Num >= 0)), 0L);
#line 1104
  if (tmp___1) {
#line 1104
    __assert_rtn("Database_open", "test/database.c", 64, "Num >=0");
  }
#line 1105
  if (! conn->db) {
#line 1105
    die("Memory error");
  }
#line 1106
  if ((int )mode == 99) {
#line 1107
    conn->file = fopen(filename, "w");
  } else {
#line 1109
    conn->file = fopen(filename, "r+");
#line 1110
    if (conn->file) {
#line 1111
      Database_load(conn);
    }
  }
#line 1114
  if (! conn->file) {
#line 1114
    die("Failed to open the file");
  }
#line 1115
  return (conn);
}
}
#line 1117 "tr.c"
void Database_close(struct Connection *conn ) 
{ 


  {
  {
#line 1120
  if (conn->file) {
#line 1121
    fclose(conn->file);
  }
#line 1122
  if (conn->db) {
#line 1124
    free((void *)conn->db);
#line 1125
    Num ++;
  }
#line 1127
  free((void *)conn);
#line 1128
  Num ++;
  }
#line 1130
  return;
}
}
#line 1131 "tr.c"
void Database_write(struct Connection *conn ) 
{ 
  int rc ;
  int tmp ;

  {
#line 1133
  rewind(conn->file);
#line 1134
  tmp = (int )fwrite((void const   *)conn->db, sizeof(struct Database ), (size_t )1, conn->file);
#line 1134
  rc = tmp;
#line 1135
  if (rc != 1) {
#line 1135
    die("Failed to write database.");
  }
#line 1136
  rc = fflush(conn->file);
#line 1137
  if (rc == -1) {
#line 1137
    die("Cannot flush database.");
  }
#line 1138
  return;
}
}
#line 1139 "tr.c"
void Database_create(struct Connection *conn ) 
{ 
  int i ;
  struct Address addr ;

  {
#line 1141
  i = 0;
#line 1142
  i = 0;
#line 1142
  while (i < 100) {
#line 1143
    addr.id = i;
#line 1143
    addr.set = 0;
#line 1143
    addr.name[0] = (char)0;
#line 1143
    addr.name[1] = (char)0;
#line 1143
    addr.name[2] = (char)0;
#line 1143
    addr.name[3] = (char)0;
#line 1143
    addr.name[4] = (char)0;
#line 1143
    addr.name[5] = (char)0;
#line 1143
    addr.name[6] = (char)0;
#line 1143
    addr.name[7] = (char)0;
#line 1143
    addr.name[8] = (char)0;
#line 1143
    addr.name[9] = (char)0;
#line 1143
    addr.name[10] = (char)0;
#line 1143
    addr.name[11] = (char)0;
#line 1143
    addr.name[12] = (char)0;
#line 1143
    addr.name[13] = (char)0;
#line 1143
    addr.name[14] = (char)0;
#line 1143
    addr.name[15] = (char)0;
#line 1143
    addr.name[16] = (char)0;
#line 1143
    addr.name[17] = (char)0;
#line 1143
    addr.name[18] = (char)0;
#line 1143
    addr.name[19] = (char)0;
#line 1143
    addr.name[20] = (char)0;
#line 1143
    addr.name[21] = (char)0;
#line 1143
    addr.name[22] = (char)0;
#line 1143
    addr.name[23] = (char)0;
#line 1143
    addr.name[24] = (char)0;
#line 1143
    addr.name[25] = (char)0;
#line 1143
    addr.name[26] = (char)0;
#line 1143
    addr.name[27] = (char)0;
#line 1143
    addr.name[28] = (char)0;
#line 1143
    addr.name[29] = (char)0;
#line 1143
    addr.name[30] = (char)0;
#line 1143
    addr.name[31] = (char)0;
#line 1143
    addr.name[32] = (char)0;
#line 1143
    addr.name[33] = (char)0;
#line 1143
    addr.name[34] = (char)0;
#line 1143
    addr.name[35] = (char)0;
#line 1143
    addr.name[36] = (char)0;
#line 1143
    addr.name[37] = (char)0;
#line 1143
    addr.name[38] = (char)0;
#line 1143
    addr.name[39] = (char)0;
#line 1143
    addr.name[40] = (char)0;
#line 1143
    addr.name[41] = (char)0;
#line 1143
    addr.name[42] = (char)0;
#line 1143
    addr.name[43] = (char)0;
#line 1143
    addr.name[44] = (char)0;
#line 1143
    addr.name[45] = (char)0;
#line 1143
    addr.name[46] = (char)0;
#line 1143
    addr.name[47] = (char)0;
#line 1143
    addr.name[48] = (char)0;
#line 1143
    addr.name[49] = (char)0;
#line 1143
    addr.name[50] = (char)0;
#line 1143
    addr.name[51] = (char)0;
#line 1143
    addr.name[52] = (char)0;
#line 1143
    addr.name[53] = (char)0;
#line 1143
    addr.name[54] = (char)0;
#line 1143
    addr.name[55] = (char)0;
#line 1143
    addr.name[56] = (char)0;
#line 1143
    addr.name[57] = (char)0;
#line 1143
    addr.name[58] = (char)0;
#line 1143
    addr.name[59] = (char)0;
#line 1143
    addr.name[60] = (char)0;
#line 1143
    addr.name[61] = (char)0;
#line 1143
    addr.name[62] = (char)0;
#line 1143
    addr.name[63] = (char)0;
#line 1143
    addr.name[64] = (char)0;
#line 1143
    addr.name[65] = (char)0;
#line 1143
    addr.name[66] = (char)0;
#line 1143
    addr.name[67] = (char)0;
#line 1143
    addr.name[68] = (char)0;
#line 1143
    addr.name[69] = (char)0;
#line 1143
    addr.name[70] = (char)0;
#line 1143
    addr.name[71] = (char)0;
#line 1143
    addr.name[72] = (char)0;
#line 1143
    addr.name[73] = (char)0;
#line 1143
    addr.name[74] = (char)0;
#line 1143
    addr.name[75] = (char)0;
#line 1143
    addr.name[76] = (char)0;
#line 1143
    addr.name[77] = (char)0;
#line 1143
    addr.name[78] = (char)0;
#line 1143
    addr.name[79] = (char)0;
#line 1143
    addr.name[80] = (char)0;
#line 1143
    addr.name[81] = (char)0;
#line 1143
    addr.name[82] = (char)0;
#line 1143
    addr.name[83] = (char)0;
#line 1143
    addr.name[84] = (char)0;
#line 1143
    addr.name[85] = (char)0;
#line 1143
    addr.name[86] = (char)0;
#line 1143
    addr.name[87] = (char)0;
#line 1143
    addr.name[88] = (char)0;
#line 1143
    addr.name[89] = (char)0;
#line 1143
    addr.name[90] = (char)0;
#line 1143
    addr.name[91] = (char)0;
#line 1143
    addr.name[92] = (char)0;
#line 1143
    addr.name[93] = (char)0;
#line 1143
    addr.name[94] = (char)0;
#line 1143
    addr.name[95] = (char)0;
#line 1143
    addr.name[96] = (char)0;
#line 1143
    addr.name[97] = (char)0;
#line 1143
    addr.name[98] = (char)0;
#line 1143
    addr.name[99] = (char)0;
#line 1143
    addr.name[100] = (char)0;
#line 1143
    addr.name[101] = (char)0;
#line 1143
    addr.name[102] = (char)0;
#line 1143
    addr.name[103] = (char)0;
#line 1143
    addr.name[104] = (char)0;
#line 1143
    addr.name[105] = (char)0;
#line 1143
    addr.name[106] = (char)0;
#line 1143
    addr.name[107] = (char)0;
#line 1143
    addr.name[108] = (char)0;
#line 1143
    addr.name[109] = (char)0;
#line 1143
    addr.name[110] = (char)0;
#line 1143
    addr.name[111] = (char)0;
#line 1143
    addr.name[112] = (char)0;
#line 1143
    addr.name[113] = (char)0;
#line 1143
    addr.name[114] = (char)0;
#line 1143
    addr.name[115] = (char)0;
#line 1143
    addr.name[116] = (char)0;
#line 1143
    addr.name[117] = (char)0;
#line 1143
    addr.name[118] = (char)0;
#line 1143
    addr.name[119] = (char)0;
#line 1143
    addr.name[120] = (char)0;
#line 1143
    addr.name[121] = (char)0;
#line 1143
    addr.name[122] = (char)0;
#line 1143
    addr.name[123] = (char)0;
#line 1143
    addr.name[124] = (char)0;
#line 1143
    addr.name[125] = (char)0;
#line 1143
    addr.name[126] = (char)0;
#line 1143
    addr.name[127] = (char)0;
#line 1143
    addr.name[128] = (char)0;
#line 1143
    addr.name[129] = (char)0;
#line 1143
    addr.name[130] = (char)0;
#line 1143
    addr.name[131] = (char)0;
#line 1143
    addr.name[132] = (char)0;
#line 1143
    addr.name[133] = (char)0;
#line 1143
    addr.name[134] = (char)0;
#line 1143
    addr.name[135] = (char)0;
#line 1143
    addr.name[136] = (char)0;
#line 1143
    addr.name[137] = (char)0;
#line 1143
    addr.name[138] = (char)0;
#line 1143
    addr.name[139] = (char)0;
#line 1143
    addr.name[140] = (char)0;
#line 1143
    addr.name[141] = (char)0;
#line 1143
    addr.name[142] = (char)0;
#line 1143
    addr.name[143] = (char)0;
#line 1143
    addr.name[144] = (char)0;
#line 1143
    addr.name[145] = (char)0;
#line 1143
    addr.name[146] = (char)0;
#line 1143
    addr.name[147] = (char)0;
#line 1143
    addr.name[148] = (char)0;
#line 1143
    addr.name[149] = (char)0;
#line 1143
    addr.name[150] = (char)0;
#line 1143
    addr.name[151] = (char)0;
#line 1143
    addr.name[152] = (char)0;
#line 1143
    addr.name[153] = (char)0;
#line 1143
    addr.name[154] = (char)0;
#line 1143
    addr.name[155] = (char)0;
#line 1143
    addr.name[156] = (char)0;
#line 1143
    addr.name[157] = (char)0;
#line 1143
    addr.name[158] = (char)0;
#line 1143
    addr.name[159] = (char)0;
#line 1143
    addr.name[160] = (char)0;
#line 1143
    addr.name[161] = (char)0;
#line 1143
    addr.name[162] = (char)0;
#line 1143
    addr.name[163] = (char)0;
#line 1143
    addr.name[164] = (char)0;
#line 1143
    addr.name[165] = (char)0;
#line 1143
    addr.name[166] = (char)0;
#line 1143
    addr.name[167] = (char)0;
#line 1143
    addr.name[168] = (char)0;
#line 1143
    addr.name[169] = (char)0;
#line 1143
    addr.name[170] = (char)0;
#line 1143
    addr.name[171] = (char)0;
#line 1143
    addr.name[172] = (char)0;
#line 1143
    addr.name[173] = (char)0;
#line 1143
    addr.name[174] = (char)0;
#line 1143
    addr.name[175] = (char)0;
#line 1143
    addr.name[176] = (char)0;
#line 1143
    addr.name[177] = (char)0;
#line 1143
    addr.name[178] = (char)0;
#line 1143
    addr.name[179] = (char)0;
#line 1143
    addr.name[180] = (char)0;
#line 1143
    addr.name[181] = (char)0;
#line 1143
    addr.name[182] = (char)0;
#line 1143
    addr.name[183] = (char)0;
#line 1143
    addr.name[184] = (char)0;
#line 1143
    addr.name[185] = (char)0;
#line 1143
    addr.name[186] = (char)0;
#line 1143
    addr.name[187] = (char)0;
#line 1143
    addr.name[188] = (char)0;
#line 1143
    addr.name[189] = (char)0;
#line 1143
    addr.name[190] = (char)0;
#line 1143
    addr.name[191] = (char)0;
#line 1143
    addr.name[192] = (char)0;
#line 1143
    addr.name[193] = (char)0;
#line 1143
    addr.name[194] = (char)0;
#line 1143
    addr.name[195] = (char)0;
#line 1143
    addr.name[196] = (char)0;
#line 1143
    addr.name[197] = (char)0;
#line 1143
    addr.name[198] = (char)0;
#line 1143
    addr.name[199] = (char)0;
#line 1143
    addr.name[200] = (char)0;
#line 1143
    addr.name[201] = (char)0;
#line 1143
    addr.name[202] = (char)0;
#line 1143
    addr.name[203] = (char)0;
#line 1143
    addr.name[204] = (char)0;
#line 1143
    addr.name[205] = (char)0;
#line 1143
    addr.name[206] = (char)0;
#line 1143
    addr.name[207] = (char)0;
#line 1143
    addr.name[208] = (char)0;
#line 1143
    addr.name[209] = (char)0;
#line 1143
    addr.name[210] = (char)0;
#line 1143
    addr.name[211] = (char)0;
#line 1143
    addr.name[212] = (char)0;
#line 1143
    addr.name[213] = (char)0;
#line 1143
    addr.name[214] = (char)0;
#line 1143
    addr.name[215] = (char)0;
#line 1143
    addr.name[216] = (char)0;
#line 1143
    addr.name[217] = (char)0;
#line 1143
    addr.name[218] = (char)0;
#line 1143
    addr.name[219] = (char)0;
#line 1143
    addr.name[220] = (char)0;
#line 1143
    addr.name[221] = (char)0;
#line 1143
    addr.name[222] = (char)0;
#line 1143
    addr.name[223] = (char)0;
#line 1143
    addr.name[224] = (char)0;
#line 1143
    addr.name[225] = (char)0;
#line 1143
    addr.name[226] = (char)0;
#line 1143
    addr.name[227] = (char)0;
#line 1143
    addr.name[228] = (char)0;
#line 1143
    addr.name[229] = (char)0;
#line 1143
    addr.name[230] = (char)0;
#line 1143
    addr.name[231] = (char)0;
#line 1143
    addr.name[232] = (char)0;
#line 1143
    addr.name[233] = (char)0;
#line 1143
    addr.name[234] = (char)0;
#line 1143
    addr.name[235] = (char)0;
#line 1143
    addr.name[236] = (char)0;
#line 1143
    addr.name[237] = (char)0;
#line 1143
    addr.name[238] = (char)0;
#line 1143
    addr.name[239] = (char)0;
#line 1143
    addr.name[240] = (char)0;
#line 1143
    addr.name[241] = (char)0;
#line 1143
    addr.name[242] = (char)0;
#line 1143
    addr.name[243] = (char)0;
#line 1143
    addr.name[244] = (char)0;
#line 1143
    addr.name[245] = (char)0;
#line 1143
    addr.name[246] = (char)0;
#line 1143
    addr.name[247] = (char)0;
#line 1143
    addr.name[248] = (char)0;
#line 1143
    addr.name[249] = (char)0;
#line 1143
    addr.name[250] = (char)0;
#line 1143
    addr.name[251] = (char)0;
#line 1143
    addr.name[252] = (char)0;
#line 1143
    addr.name[253] = (char)0;
#line 1143
    addr.name[254] = (char)0;
#line 1143
    addr.name[255] = (char)0;
#line 1143
    addr.name[256] = (char)0;
#line 1143
    addr.name[257] = (char)0;
#line 1143
    addr.name[258] = (char)0;
#line 1143
    addr.name[259] = (char)0;
#line 1143
    addr.name[260] = (char)0;
#line 1143
    addr.name[261] = (char)0;
#line 1143
    addr.name[262] = (char)0;
#line 1143
    addr.name[263] = (char)0;
#line 1143
    addr.name[264] = (char)0;
#line 1143
    addr.name[265] = (char)0;
#line 1143
    addr.name[266] = (char)0;
#line 1143
    addr.name[267] = (char)0;
#line 1143
    addr.name[268] = (char)0;
#line 1143
    addr.name[269] = (char)0;
#line 1143
    addr.name[270] = (char)0;
#line 1143
    addr.name[271] = (char)0;
#line 1143
    addr.name[272] = (char)0;
#line 1143
    addr.name[273] = (char)0;
#line 1143
    addr.name[274] = (char)0;
#line 1143
    addr.name[275] = (char)0;
#line 1143
    addr.name[276] = (char)0;
#line 1143
    addr.name[277] = (char)0;
#line 1143
    addr.name[278] = (char)0;
#line 1143
    addr.name[279] = (char)0;
#line 1143
    addr.name[280] = (char)0;
#line 1143
    addr.name[281] = (char)0;
#line 1143
    addr.name[282] = (char)0;
#line 1143
    addr.name[283] = (char)0;
#line 1143
    addr.name[284] = (char)0;
#line 1143
    addr.name[285] = (char)0;
#line 1143
    addr.name[286] = (char)0;
#line 1143
    addr.name[287] = (char)0;
#line 1143
    addr.name[288] = (char)0;
#line 1143
    addr.name[289] = (char)0;
#line 1143
    addr.name[290] = (char)0;
#line 1143
    addr.name[291] = (char)0;
#line 1143
    addr.name[292] = (char)0;
#line 1143
    addr.name[293] = (char)0;
#line 1143
    addr.name[294] = (char)0;
#line 1143
    addr.name[295] = (char)0;
#line 1143
    addr.name[296] = (char)0;
#line 1143
    addr.name[297] = (char)0;
#line 1143
    addr.name[298] = (char)0;
#line 1143
    addr.name[299] = (char)0;
#line 1143
    addr.name[300] = (char)0;
#line 1143
    addr.name[301] = (char)0;
#line 1143
    addr.name[302] = (char)0;
#line 1143
    addr.name[303] = (char)0;
#line 1143
    addr.name[304] = (char)0;
#line 1143
    addr.name[305] = (char)0;
#line 1143
    addr.name[306] = (char)0;
#line 1143
    addr.name[307] = (char)0;
#line 1143
    addr.name[308] = (char)0;
#line 1143
    addr.name[309] = (char)0;
#line 1143
    addr.name[310] = (char)0;
#line 1143
    addr.name[311] = (char)0;
#line 1143
    addr.name[312] = (char)0;
#line 1143
    addr.name[313] = (char)0;
#line 1143
    addr.name[314] = (char)0;
#line 1143
    addr.name[315] = (char)0;
#line 1143
    addr.name[316] = (char)0;
#line 1143
    addr.name[317] = (char)0;
#line 1143
    addr.name[318] = (char)0;
#line 1143
    addr.name[319] = (char)0;
#line 1143
    addr.name[320] = (char)0;
#line 1143
    addr.name[321] = (char)0;
#line 1143
    addr.name[322] = (char)0;
#line 1143
    addr.name[323] = (char)0;
#line 1143
    addr.name[324] = (char)0;
#line 1143
    addr.name[325] = (char)0;
#line 1143
    addr.name[326] = (char)0;
#line 1143
    addr.name[327] = (char)0;
#line 1143
    addr.name[328] = (char)0;
#line 1143
    addr.name[329] = (char)0;
#line 1143
    addr.name[330] = (char)0;
#line 1143
    addr.name[331] = (char)0;
#line 1143
    addr.name[332] = (char)0;
#line 1143
    addr.name[333] = (char)0;
#line 1143
    addr.name[334] = (char)0;
#line 1143
    addr.name[335] = (char)0;
#line 1143
    addr.name[336] = (char)0;
#line 1143
    addr.name[337] = (char)0;
#line 1143
    addr.name[338] = (char)0;
#line 1143
    addr.name[339] = (char)0;
#line 1143
    addr.name[340] = (char)0;
#line 1143
    addr.name[341] = (char)0;
#line 1143
    addr.name[342] = (char)0;
#line 1143
    addr.name[343] = (char)0;
#line 1143
    addr.name[344] = (char)0;
#line 1143
    addr.name[345] = (char)0;
#line 1143
    addr.name[346] = (char)0;
#line 1143
    addr.name[347] = (char)0;
#line 1143
    addr.name[348] = (char)0;
#line 1143
    addr.name[349] = (char)0;
#line 1143
    addr.name[350] = (char)0;
#line 1143
    addr.name[351] = (char)0;
#line 1143
    addr.name[352] = (char)0;
#line 1143
    addr.name[353] = (char)0;
#line 1143
    addr.name[354] = (char)0;
#line 1143
    addr.name[355] = (char)0;
#line 1143
    addr.name[356] = (char)0;
#line 1143
    addr.name[357] = (char)0;
#line 1143
    addr.name[358] = (char)0;
#line 1143
    addr.name[359] = (char)0;
#line 1143
    addr.name[360] = (char)0;
#line 1143
    addr.name[361] = (char)0;
#line 1143
    addr.name[362] = (char)0;
#line 1143
    addr.name[363] = (char)0;
#line 1143
    addr.name[364] = (char)0;
#line 1143
    addr.name[365] = (char)0;
#line 1143
    addr.name[366] = (char)0;
#line 1143
    addr.name[367] = (char)0;
#line 1143
    addr.name[368] = (char)0;
#line 1143
    addr.name[369] = (char)0;
#line 1143
    addr.name[370] = (char)0;
#line 1143
    addr.name[371] = (char)0;
#line 1143
    addr.name[372] = (char)0;
#line 1143
    addr.name[373] = (char)0;
#line 1143
    addr.name[374] = (char)0;
#line 1143
    addr.name[375] = (char)0;
#line 1143
    addr.name[376] = (char)0;
#line 1143
    addr.name[377] = (char)0;
#line 1143
    addr.name[378] = (char)0;
#line 1143
    addr.name[379] = (char)0;
#line 1143
    addr.name[380] = (char)0;
#line 1143
    addr.name[381] = (char)0;
#line 1143
    addr.name[382] = (char)0;
#line 1143
    addr.name[383] = (char)0;
#line 1143
    addr.name[384] = (char)0;
#line 1143
    addr.name[385] = (char)0;
#line 1143
    addr.name[386] = (char)0;
#line 1143
    addr.name[387] = (char)0;
#line 1143
    addr.name[388] = (char)0;
#line 1143
    addr.name[389] = (char)0;
#line 1143
    addr.name[390] = (char)0;
#line 1143
    addr.name[391] = (char)0;
#line 1143
    addr.name[392] = (char)0;
#line 1143
    addr.name[393] = (char)0;
#line 1143
    addr.name[394] = (char)0;
#line 1143
    addr.name[395] = (char)0;
#line 1143
    addr.name[396] = (char)0;
#line 1143
    addr.name[397] = (char)0;
#line 1143
    addr.name[398] = (char)0;
#line 1143
    addr.name[399] = (char)0;
#line 1143
    addr.name[400] = (char)0;
#line 1143
    addr.name[401] = (char)0;
#line 1143
    addr.name[402] = (char)0;
#line 1143
    addr.name[403] = (char)0;
#line 1143
    addr.name[404] = (char)0;
#line 1143
    addr.name[405] = (char)0;
#line 1143
    addr.name[406] = (char)0;
#line 1143
    addr.name[407] = (char)0;
#line 1143
    addr.name[408] = (char)0;
#line 1143
    addr.name[409] = (char)0;
#line 1143
    addr.name[410] = (char)0;
#line 1143
    addr.name[411] = (char)0;
#line 1143
    addr.name[412] = (char)0;
#line 1143
    addr.name[413] = (char)0;
#line 1143
    addr.name[414] = (char)0;
#line 1143
    addr.name[415] = (char)0;
#line 1143
    addr.name[416] = (char)0;
#line 1143
    addr.name[417] = (char)0;
#line 1143
    addr.name[418] = (char)0;
#line 1143
    addr.name[419] = (char)0;
#line 1143
    addr.name[420] = (char)0;
#line 1143
    addr.name[421] = (char)0;
#line 1143
    addr.name[422] = (char)0;
#line 1143
    addr.name[423] = (char)0;
#line 1143
    addr.name[424] = (char)0;
#line 1143
    addr.name[425] = (char)0;
#line 1143
    addr.name[426] = (char)0;
#line 1143
    addr.name[427] = (char)0;
#line 1143
    addr.name[428] = (char)0;
#line 1143
    addr.name[429] = (char)0;
#line 1143
    addr.name[430] = (char)0;
#line 1143
    addr.name[431] = (char)0;
#line 1143
    addr.name[432] = (char)0;
#line 1143
    addr.name[433] = (char)0;
#line 1143
    addr.name[434] = (char)0;
#line 1143
    addr.name[435] = (char)0;
#line 1143
    addr.name[436] = (char)0;
#line 1143
    addr.name[437] = (char)0;
#line 1143
    addr.name[438] = (char)0;
#line 1143
    addr.name[439] = (char)0;
#line 1143
    addr.name[440] = (char)0;
#line 1143
    addr.name[441] = (char)0;
#line 1143
    addr.name[442] = (char)0;
#line 1143
    addr.name[443] = (char)0;
#line 1143
    addr.name[444] = (char)0;
#line 1143
    addr.name[445] = (char)0;
#line 1143
    addr.name[446] = (char)0;
#line 1143
    addr.name[447] = (char)0;
#line 1143
    addr.name[448] = (char)0;
#line 1143
    addr.name[449] = (char)0;
#line 1143
    addr.name[450] = (char)0;
#line 1143
    addr.name[451] = (char)0;
#line 1143
    addr.name[452] = (char)0;
#line 1143
    addr.name[453] = (char)0;
#line 1143
    addr.name[454] = (char)0;
#line 1143
    addr.name[455] = (char)0;
#line 1143
    addr.name[456] = (char)0;
#line 1143
    addr.name[457] = (char)0;
#line 1143
    addr.name[458] = (char)0;
#line 1143
    addr.name[459] = (char)0;
#line 1143
    addr.name[460] = (char)0;
#line 1143
    addr.name[461] = (char)0;
#line 1143
    addr.name[462] = (char)0;
#line 1143
    addr.name[463] = (char)0;
#line 1143
    addr.name[464] = (char)0;
#line 1143
    addr.name[465] = (char)0;
#line 1143
    addr.name[466] = (char)0;
#line 1143
    addr.name[467] = (char)0;
#line 1143
    addr.name[468] = (char)0;
#line 1143
    addr.name[469] = (char)0;
#line 1143
    addr.name[470] = (char)0;
#line 1143
    addr.name[471] = (char)0;
#line 1143
    addr.name[472] = (char)0;
#line 1143
    addr.name[473] = (char)0;
#line 1143
    addr.name[474] = (char)0;
#line 1143
    addr.name[475] = (char)0;
#line 1143
    addr.name[476] = (char)0;
#line 1143
    addr.name[477] = (char)0;
#line 1143
    addr.name[478] = (char)0;
#line 1143
    addr.name[479] = (char)0;
#line 1143
    addr.name[480] = (char)0;
#line 1143
    addr.name[481] = (char)0;
#line 1143
    addr.name[482] = (char)0;
#line 1143
    addr.name[483] = (char)0;
#line 1143
    addr.name[484] = (char)0;
#line 1143
    addr.name[485] = (char)0;
#line 1143
    addr.name[486] = (char)0;
#line 1143
    addr.name[487] = (char)0;
#line 1143
    addr.name[488] = (char)0;
#line 1143
    addr.name[489] = (char)0;
#line 1143
    addr.name[490] = (char)0;
#line 1143
    addr.name[491] = (char)0;
#line 1143
    addr.name[492] = (char)0;
#line 1143
    addr.name[493] = (char)0;
#line 1143
    addr.name[494] = (char)0;
#line 1143
    addr.name[495] = (char)0;
#line 1143
    addr.name[496] = (char)0;
#line 1143
    addr.name[497] = (char)0;
#line 1143
    addr.name[498] = (char)0;
#line 1143
    addr.name[499] = (char)0;
#line 1143
    addr.name[500] = (char)0;
#line 1143
    addr.name[501] = (char)0;
#line 1143
    addr.name[502] = (char)0;
#line 1143
    addr.name[503] = (char)0;
#line 1143
    addr.name[504] = (char)0;
#line 1143
    addr.name[505] = (char)0;
#line 1143
    addr.name[506] = (char)0;
#line 1143
    addr.name[507] = (char)0;
#line 1143
    addr.name[508] = (char)0;
#line 1143
    addr.name[509] = (char)0;
#line 1143
    addr.name[510] = (char)0;
#line 1143
    addr.name[511] = (char)0;
#line 1143
    addr.email[0] = (char)0;
#line 1143
    addr.email[1] = (char)0;
#line 1143
    addr.email[2] = (char)0;
#line 1143
    addr.email[3] = (char)0;
#line 1143
    addr.email[4] = (char)0;
#line 1143
    addr.email[5] = (char)0;
#line 1143
    addr.email[6] = (char)0;
#line 1143
    addr.email[7] = (char)0;
#line 1143
    addr.email[8] = (char)0;
#line 1143
    addr.email[9] = (char)0;
#line 1143
    addr.email[10] = (char)0;
#line 1143
    addr.email[11] = (char)0;
#line 1143
    addr.email[12] = (char)0;
#line 1143
    addr.email[13] = (char)0;
#line 1143
    addr.email[14] = (char)0;
#line 1143
    addr.email[15] = (char)0;
#line 1143
    addr.email[16] = (char)0;
#line 1143
    addr.email[17] = (char)0;
#line 1143
    addr.email[18] = (char)0;
#line 1143
    addr.email[19] = (char)0;
#line 1143
    addr.email[20] = (char)0;
#line 1143
    addr.email[21] = (char)0;
#line 1143
    addr.email[22] = (char)0;
#line 1143
    addr.email[23] = (char)0;
#line 1143
    addr.email[24] = (char)0;
#line 1143
    addr.email[25] = (char)0;
#line 1143
    addr.email[26] = (char)0;
#line 1143
    addr.email[27] = (char)0;
#line 1143
    addr.email[28] = (char)0;
#line 1143
    addr.email[29] = (char)0;
#line 1143
    addr.email[30] = (char)0;
#line 1143
    addr.email[31] = (char)0;
#line 1143
    addr.email[32] = (char)0;
#line 1143
    addr.email[33] = (char)0;
#line 1143
    addr.email[34] = (char)0;
#line 1143
    addr.email[35] = (char)0;
#line 1143
    addr.email[36] = (char)0;
#line 1143
    addr.email[37] = (char)0;
#line 1143
    addr.email[38] = (char)0;
#line 1143
    addr.email[39] = (char)0;
#line 1143
    addr.email[40] = (char)0;
#line 1143
    addr.email[41] = (char)0;
#line 1143
    addr.email[42] = (char)0;
#line 1143
    addr.email[43] = (char)0;
#line 1143
    addr.email[44] = (char)0;
#line 1143
    addr.email[45] = (char)0;
#line 1143
    addr.email[46] = (char)0;
#line 1143
    addr.email[47] = (char)0;
#line 1143
    addr.email[48] = (char)0;
#line 1143
    addr.email[49] = (char)0;
#line 1143
    addr.email[50] = (char)0;
#line 1143
    addr.email[51] = (char)0;
#line 1143
    addr.email[52] = (char)0;
#line 1143
    addr.email[53] = (char)0;
#line 1143
    addr.email[54] = (char)0;
#line 1143
    addr.email[55] = (char)0;
#line 1143
    addr.email[56] = (char)0;
#line 1143
    addr.email[57] = (char)0;
#line 1143
    addr.email[58] = (char)0;
#line 1143
    addr.email[59] = (char)0;
#line 1143
    addr.email[60] = (char)0;
#line 1143
    addr.email[61] = (char)0;
#line 1143
    addr.email[62] = (char)0;
#line 1143
    addr.email[63] = (char)0;
#line 1143
    addr.email[64] = (char)0;
#line 1143
    addr.email[65] = (char)0;
#line 1143
    addr.email[66] = (char)0;
#line 1143
    addr.email[67] = (char)0;
#line 1143
    addr.email[68] = (char)0;
#line 1143
    addr.email[69] = (char)0;
#line 1143
    addr.email[70] = (char)0;
#line 1143
    addr.email[71] = (char)0;
#line 1143
    addr.email[72] = (char)0;
#line 1143
    addr.email[73] = (char)0;
#line 1143
    addr.email[74] = (char)0;
#line 1143
    addr.email[75] = (char)0;
#line 1143
    addr.email[76] = (char)0;
#line 1143
    addr.email[77] = (char)0;
#line 1143
    addr.email[78] = (char)0;
#line 1143
    addr.email[79] = (char)0;
#line 1143
    addr.email[80] = (char)0;
#line 1143
    addr.email[81] = (char)0;
#line 1143
    addr.email[82] = (char)0;
#line 1143
    addr.email[83] = (char)0;
#line 1143
    addr.email[84] = (char)0;
#line 1143
    addr.email[85] = (char)0;
#line 1143
    addr.email[86] = (char)0;
#line 1143
    addr.email[87] = (char)0;
#line 1143
    addr.email[88] = (char)0;
#line 1143
    addr.email[89] = (char)0;
#line 1143
    addr.email[90] = (char)0;
#line 1143
    addr.email[91] = (char)0;
#line 1143
    addr.email[92] = (char)0;
#line 1143
    addr.email[93] = (char)0;
#line 1143
    addr.email[94] = (char)0;
#line 1143
    addr.email[95] = (char)0;
#line 1143
    addr.email[96] = (char)0;
#line 1143
    addr.email[97] = (char)0;
#line 1143
    addr.email[98] = (char)0;
#line 1143
    addr.email[99] = (char)0;
#line 1143
    addr.email[100] = (char)0;
#line 1143
    addr.email[101] = (char)0;
#line 1143
    addr.email[102] = (char)0;
#line 1143
    addr.email[103] = (char)0;
#line 1143
    addr.email[104] = (char)0;
#line 1143
    addr.email[105] = (char)0;
#line 1143
    addr.email[106] = (char)0;
#line 1143
    addr.email[107] = (char)0;
#line 1143
    addr.email[108] = (char)0;
#line 1143
    addr.email[109] = (char)0;
#line 1143
    addr.email[110] = (char)0;
#line 1143
    addr.email[111] = (char)0;
#line 1143
    addr.email[112] = (char)0;
#line 1143
    addr.email[113] = (char)0;
#line 1143
    addr.email[114] = (char)0;
#line 1143
    addr.email[115] = (char)0;
#line 1143
    addr.email[116] = (char)0;
#line 1143
    addr.email[117] = (char)0;
#line 1143
    addr.email[118] = (char)0;
#line 1143
    addr.email[119] = (char)0;
#line 1143
    addr.email[120] = (char)0;
#line 1143
    addr.email[121] = (char)0;
#line 1143
    addr.email[122] = (char)0;
#line 1143
    addr.email[123] = (char)0;
#line 1143
    addr.email[124] = (char)0;
#line 1143
    addr.email[125] = (char)0;
#line 1143
    addr.email[126] = (char)0;
#line 1143
    addr.email[127] = (char)0;
#line 1143
    addr.email[128] = (char)0;
#line 1143
    addr.email[129] = (char)0;
#line 1143
    addr.email[130] = (char)0;
#line 1143
    addr.email[131] = (char)0;
#line 1143
    addr.email[132] = (char)0;
#line 1143
    addr.email[133] = (char)0;
#line 1143
    addr.email[134] = (char)0;
#line 1143
    addr.email[135] = (char)0;
#line 1143
    addr.email[136] = (char)0;
#line 1143
    addr.email[137] = (char)0;
#line 1143
    addr.email[138] = (char)0;
#line 1143
    addr.email[139] = (char)0;
#line 1143
    addr.email[140] = (char)0;
#line 1143
    addr.email[141] = (char)0;
#line 1143
    addr.email[142] = (char)0;
#line 1143
    addr.email[143] = (char)0;
#line 1143
    addr.email[144] = (char)0;
#line 1143
    addr.email[145] = (char)0;
#line 1143
    addr.email[146] = (char)0;
#line 1143
    addr.email[147] = (char)0;
#line 1143
    addr.email[148] = (char)0;
#line 1143
    addr.email[149] = (char)0;
#line 1143
    addr.email[150] = (char)0;
#line 1143
    addr.email[151] = (char)0;
#line 1143
    addr.email[152] = (char)0;
#line 1143
    addr.email[153] = (char)0;
#line 1143
    addr.email[154] = (char)0;
#line 1143
    addr.email[155] = (char)0;
#line 1143
    addr.email[156] = (char)0;
#line 1143
    addr.email[157] = (char)0;
#line 1143
    addr.email[158] = (char)0;
#line 1143
    addr.email[159] = (char)0;
#line 1143
    addr.email[160] = (char)0;
#line 1143
    addr.email[161] = (char)0;
#line 1143
    addr.email[162] = (char)0;
#line 1143
    addr.email[163] = (char)0;
#line 1143
    addr.email[164] = (char)0;
#line 1143
    addr.email[165] = (char)0;
#line 1143
    addr.email[166] = (char)0;
#line 1143
    addr.email[167] = (char)0;
#line 1143
    addr.email[168] = (char)0;
#line 1143
    addr.email[169] = (char)0;
#line 1143
    addr.email[170] = (char)0;
#line 1143
    addr.email[171] = (char)0;
#line 1143
    addr.email[172] = (char)0;
#line 1143
    addr.email[173] = (char)0;
#line 1143
    addr.email[174] = (char)0;
#line 1143
    addr.email[175] = (char)0;
#line 1143
    addr.email[176] = (char)0;
#line 1143
    addr.email[177] = (char)0;
#line 1143
    addr.email[178] = (char)0;
#line 1143
    addr.email[179] = (char)0;
#line 1143
    addr.email[180] = (char)0;
#line 1143
    addr.email[181] = (char)0;
#line 1143
    addr.email[182] = (char)0;
#line 1143
    addr.email[183] = (char)0;
#line 1143
    addr.email[184] = (char)0;
#line 1143
    addr.email[185] = (char)0;
#line 1143
    addr.email[186] = (char)0;
#line 1143
    addr.email[187] = (char)0;
#line 1143
    addr.email[188] = (char)0;
#line 1143
    addr.email[189] = (char)0;
#line 1143
    addr.email[190] = (char)0;
#line 1143
    addr.email[191] = (char)0;
#line 1143
    addr.email[192] = (char)0;
#line 1143
    addr.email[193] = (char)0;
#line 1143
    addr.email[194] = (char)0;
#line 1143
    addr.email[195] = (char)0;
#line 1143
    addr.email[196] = (char)0;
#line 1143
    addr.email[197] = (char)0;
#line 1143
    addr.email[198] = (char)0;
#line 1143
    addr.email[199] = (char)0;
#line 1143
    addr.email[200] = (char)0;
#line 1143
    addr.email[201] = (char)0;
#line 1143
    addr.email[202] = (char)0;
#line 1143
    addr.email[203] = (char)0;
#line 1143
    addr.email[204] = (char)0;
#line 1143
    addr.email[205] = (char)0;
#line 1143
    addr.email[206] = (char)0;
#line 1143
    addr.email[207] = (char)0;
#line 1143
    addr.email[208] = (char)0;
#line 1143
    addr.email[209] = (char)0;
#line 1143
    addr.email[210] = (char)0;
#line 1143
    addr.email[211] = (char)0;
#line 1143
    addr.email[212] = (char)0;
#line 1143
    addr.email[213] = (char)0;
#line 1143
    addr.email[214] = (char)0;
#line 1143
    addr.email[215] = (char)0;
#line 1143
    addr.email[216] = (char)0;
#line 1143
    addr.email[217] = (char)0;
#line 1143
    addr.email[218] = (char)0;
#line 1143
    addr.email[219] = (char)0;
#line 1143
    addr.email[220] = (char)0;
#line 1143
    addr.email[221] = (char)0;
#line 1143
    addr.email[222] = (char)0;
#line 1143
    addr.email[223] = (char)0;
#line 1143
    addr.email[224] = (char)0;
#line 1143
    addr.email[225] = (char)0;
#line 1143
    addr.email[226] = (char)0;
#line 1143
    addr.email[227] = (char)0;
#line 1143
    addr.email[228] = (char)0;
#line 1143
    addr.email[229] = (char)0;
#line 1143
    addr.email[230] = (char)0;
#line 1143
    addr.email[231] = (char)0;
#line 1143
    addr.email[232] = (char)0;
#line 1143
    addr.email[233] = (char)0;
#line 1143
    addr.email[234] = (char)0;
#line 1143
    addr.email[235] = (char)0;
#line 1143
    addr.email[236] = (char)0;
#line 1143
    addr.email[237] = (char)0;
#line 1143
    addr.email[238] = (char)0;
#line 1143
    addr.email[239] = (char)0;
#line 1143
    addr.email[240] = (char)0;
#line 1143
    addr.email[241] = (char)0;
#line 1143
    addr.email[242] = (char)0;
#line 1143
    addr.email[243] = (char)0;
#line 1143
    addr.email[244] = (char)0;
#line 1143
    addr.email[245] = (char)0;
#line 1143
    addr.email[246] = (char)0;
#line 1143
    addr.email[247] = (char)0;
#line 1143
    addr.email[248] = (char)0;
#line 1143
    addr.email[249] = (char)0;
#line 1143
    addr.email[250] = (char)0;
#line 1143
    addr.email[251] = (char)0;
#line 1143
    addr.email[252] = (char)0;
#line 1143
    addr.email[253] = (char)0;
#line 1143
    addr.email[254] = (char)0;
#line 1143
    addr.email[255] = (char)0;
#line 1143
    addr.email[256] = (char)0;
#line 1143
    addr.email[257] = (char)0;
#line 1143
    addr.email[258] = (char)0;
#line 1143
    addr.email[259] = (char)0;
#line 1143
    addr.email[260] = (char)0;
#line 1143
    addr.email[261] = (char)0;
#line 1143
    addr.email[262] = (char)0;
#line 1143
    addr.email[263] = (char)0;
#line 1143
    addr.email[264] = (char)0;
#line 1143
    addr.email[265] = (char)0;
#line 1143
    addr.email[266] = (char)0;
#line 1143
    addr.email[267] = (char)0;
#line 1143
    addr.email[268] = (char)0;
#line 1143
    addr.email[269] = (char)0;
#line 1143
    addr.email[270] = (char)0;
#line 1143
    addr.email[271] = (char)0;
#line 1143
    addr.email[272] = (char)0;
#line 1143
    addr.email[273] = (char)0;
#line 1143
    addr.email[274] = (char)0;
#line 1143
    addr.email[275] = (char)0;
#line 1143
    addr.email[276] = (char)0;
#line 1143
    addr.email[277] = (char)0;
#line 1143
    addr.email[278] = (char)0;
#line 1143
    addr.email[279] = (char)0;
#line 1143
    addr.email[280] = (char)0;
#line 1143
    addr.email[281] = (char)0;
#line 1143
    addr.email[282] = (char)0;
#line 1143
    addr.email[283] = (char)0;
#line 1143
    addr.email[284] = (char)0;
#line 1143
    addr.email[285] = (char)0;
#line 1143
    addr.email[286] = (char)0;
#line 1143
    addr.email[287] = (char)0;
#line 1143
    addr.email[288] = (char)0;
#line 1143
    addr.email[289] = (char)0;
#line 1143
    addr.email[290] = (char)0;
#line 1143
    addr.email[291] = (char)0;
#line 1143
    addr.email[292] = (char)0;
#line 1143
    addr.email[293] = (char)0;
#line 1143
    addr.email[294] = (char)0;
#line 1143
    addr.email[295] = (char)0;
#line 1143
    addr.email[296] = (char)0;
#line 1143
    addr.email[297] = (char)0;
#line 1143
    addr.email[298] = (char)0;
#line 1143
    addr.email[299] = (char)0;
#line 1143
    addr.email[300] = (char)0;
#line 1143
    addr.email[301] = (char)0;
#line 1143
    addr.email[302] = (char)0;
#line 1143
    addr.email[303] = (char)0;
#line 1143
    addr.email[304] = (char)0;
#line 1143
    addr.email[305] = (char)0;
#line 1143
    addr.email[306] = (char)0;
#line 1143
    addr.email[307] = (char)0;
#line 1143
    addr.email[308] = (char)0;
#line 1143
    addr.email[309] = (char)0;
#line 1143
    addr.email[310] = (char)0;
#line 1143
    addr.email[311] = (char)0;
#line 1143
    addr.email[312] = (char)0;
#line 1143
    addr.email[313] = (char)0;
#line 1143
    addr.email[314] = (char)0;
#line 1143
    addr.email[315] = (char)0;
#line 1143
    addr.email[316] = (char)0;
#line 1143
    addr.email[317] = (char)0;
#line 1143
    addr.email[318] = (char)0;
#line 1143
    addr.email[319] = (char)0;
#line 1143
    addr.email[320] = (char)0;
#line 1143
    addr.email[321] = (char)0;
#line 1143
    addr.email[322] = (char)0;
#line 1143
    addr.email[323] = (char)0;
#line 1143
    addr.email[324] = (char)0;
#line 1143
    addr.email[325] = (char)0;
#line 1143
    addr.email[326] = (char)0;
#line 1143
    addr.email[327] = (char)0;
#line 1143
    addr.email[328] = (char)0;
#line 1143
    addr.email[329] = (char)0;
#line 1143
    addr.email[330] = (char)0;
#line 1143
    addr.email[331] = (char)0;
#line 1143
    addr.email[332] = (char)0;
#line 1143
    addr.email[333] = (char)0;
#line 1143
    addr.email[334] = (char)0;
#line 1143
    addr.email[335] = (char)0;
#line 1143
    addr.email[336] = (char)0;
#line 1143
    addr.email[337] = (char)0;
#line 1143
    addr.email[338] = (char)0;
#line 1143
    addr.email[339] = (char)0;
#line 1143
    addr.email[340] = (char)0;
#line 1143
    addr.email[341] = (char)0;
#line 1143
    addr.email[342] = (char)0;
#line 1143
    addr.email[343] = (char)0;
#line 1143
    addr.email[344] = (char)0;
#line 1143
    addr.email[345] = (char)0;
#line 1143
    addr.email[346] = (char)0;
#line 1143
    addr.email[347] = (char)0;
#line 1143
    addr.email[348] = (char)0;
#line 1143
    addr.email[349] = (char)0;
#line 1143
    addr.email[350] = (char)0;
#line 1143
    addr.email[351] = (char)0;
#line 1143
    addr.email[352] = (char)0;
#line 1143
    addr.email[353] = (char)0;
#line 1143
    addr.email[354] = (char)0;
#line 1143
    addr.email[355] = (char)0;
#line 1143
    addr.email[356] = (char)0;
#line 1143
    addr.email[357] = (char)0;
#line 1143
    addr.email[358] = (char)0;
#line 1143
    addr.email[359] = (char)0;
#line 1143
    addr.email[360] = (char)0;
#line 1143
    addr.email[361] = (char)0;
#line 1143
    addr.email[362] = (char)0;
#line 1143
    addr.email[363] = (char)0;
#line 1143
    addr.email[364] = (char)0;
#line 1143
    addr.email[365] = (char)0;
#line 1143
    addr.email[366] = (char)0;
#line 1143
    addr.email[367] = (char)0;
#line 1143
    addr.email[368] = (char)0;
#line 1143
    addr.email[369] = (char)0;
#line 1143
    addr.email[370] = (char)0;
#line 1143
    addr.email[371] = (char)0;
#line 1143
    addr.email[372] = (char)0;
#line 1143
    addr.email[373] = (char)0;
#line 1143
    addr.email[374] = (char)0;
#line 1143
    addr.email[375] = (char)0;
#line 1143
    addr.email[376] = (char)0;
#line 1143
    addr.email[377] = (char)0;
#line 1143
    addr.email[378] = (char)0;
#line 1143
    addr.email[379] = (char)0;
#line 1143
    addr.email[380] = (char)0;
#line 1143
    addr.email[381] = (char)0;
#line 1143
    addr.email[382] = (char)0;
#line 1143
    addr.email[383] = (char)0;
#line 1143
    addr.email[384] = (char)0;
#line 1143
    addr.email[385] = (char)0;
#line 1143
    addr.email[386] = (char)0;
#line 1143
    addr.email[387] = (char)0;
#line 1143
    addr.email[388] = (char)0;
#line 1143
    addr.email[389] = (char)0;
#line 1143
    addr.email[390] = (char)0;
#line 1143
    addr.email[391] = (char)0;
#line 1143
    addr.email[392] = (char)0;
#line 1143
    addr.email[393] = (char)0;
#line 1143
    addr.email[394] = (char)0;
#line 1143
    addr.email[395] = (char)0;
#line 1143
    addr.email[396] = (char)0;
#line 1143
    addr.email[397] = (char)0;
#line 1143
    addr.email[398] = (char)0;
#line 1143
    addr.email[399] = (char)0;
#line 1143
    addr.email[400] = (char)0;
#line 1143
    addr.email[401] = (char)0;
#line 1143
    addr.email[402] = (char)0;
#line 1143
    addr.email[403] = (char)0;
#line 1143
    addr.email[404] = (char)0;
#line 1143
    addr.email[405] = (char)0;
#line 1143
    addr.email[406] = (char)0;
#line 1143
    addr.email[407] = (char)0;
#line 1143
    addr.email[408] = (char)0;
#line 1143
    addr.email[409] = (char)0;
#line 1143
    addr.email[410] = (char)0;
#line 1143
    addr.email[411] = (char)0;
#line 1143
    addr.email[412] = (char)0;
#line 1143
    addr.email[413] = (char)0;
#line 1143
    addr.email[414] = (char)0;
#line 1143
    addr.email[415] = (char)0;
#line 1143
    addr.email[416] = (char)0;
#line 1143
    addr.email[417] = (char)0;
#line 1143
    addr.email[418] = (char)0;
#line 1143
    addr.email[419] = (char)0;
#line 1143
    addr.email[420] = (char)0;
#line 1143
    addr.email[421] = (char)0;
#line 1143
    addr.email[422] = (char)0;
#line 1143
    addr.email[423] = (char)0;
#line 1143
    addr.email[424] = (char)0;
#line 1143
    addr.email[425] = (char)0;
#line 1143
    addr.email[426] = (char)0;
#line 1143
    addr.email[427] = (char)0;
#line 1143
    addr.email[428] = (char)0;
#line 1143
    addr.email[429] = (char)0;
#line 1143
    addr.email[430] = (char)0;
#line 1143
    addr.email[431] = (char)0;
#line 1143
    addr.email[432] = (char)0;
#line 1143
    addr.email[433] = (char)0;
#line 1143
    addr.email[434] = (char)0;
#line 1143
    addr.email[435] = (char)0;
#line 1143
    addr.email[436] = (char)0;
#line 1143
    addr.email[437] = (char)0;
#line 1143
    addr.email[438] = (char)0;
#line 1143
    addr.email[439] = (char)0;
#line 1143
    addr.email[440] = (char)0;
#line 1143
    addr.email[441] = (char)0;
#line 1143
    addr.email[442] = (char)0;
#line 1143
    addr.email[443] = (char)0;
#line 1143
    addr.email[444] = (char)0;
#line 1143
    addr.email[445] = (char)0;
#line 1143
    addr.email[446] = (char)0;
#line 1143
    addr.email[447] = (char)0;
#line 1143
    addr.email[448] = (char)0;
#line 1143
    addr.email[449] = (char)0;
#line 1143
    addr.email[450] = (char)0;
#line 1143
    addr.email[451] = (char)0;
#line 1143
    addr.email[452] = (char)0;
#line 1143
    addr.email[453] = (char)0;
#line 1143
    addr.email[454] = (char)0;
#line 1143
    addr.email[455] = (char)0;
#line 1143
    addr.email[456] = (char)0;
#line 1143
    addr.email[457] = (char)0;
#line 1143
    addr.email[458] = (char)0;
#line 1143
    addr.email[459] = (char)0;
#line 1143
    addr.email[460] = (char)0;
#line 1143
    addr.email[461] = (char)0;
#line 1143
    addr.email[462] = (char)0;
#line 1143
    addr.email[463] = (char)0;
#line 1143
    addr.email[464] = (char)0;
#line 1143
    addr.email[465] = (char)0;
#line 1143
    addr.email[466] = (char)0;
#line 1143
    addr.email[467] = (char)0;
#line 1143
    addr.email[468] = (char)0;
#line 1143
    addr.email[469] = (char)0;
#line 1143
    addr.email[470] = (char)0;
#line 1143
    addr.email[471] = (char)0;
#line 1143
    addr.email[472] = (char)0;
#line 1143
    addr.email[473] = (char)0;
#line 1143
    addr.email[474] = (char)0;
#line 1143
    addr.email[475] = (char)0;
#line 1143
    addr.email[476] = (char)0;
#line 1143
    addr.email[477] = (char)0;
#line 1143
    addr.email[478] = (char)0;
#line 1143
    addr.email[479] = (char)0;
#line 1143
    addr.email[480] = (char)0;
#line 1143
    addr.email[481] = (char)0;
#line 1143
    addr.email[482] = (char)0;
#line 1143
    addr.email[483] = (char)0;
#line 1143
    addr.email[484] = (char)0;
#line 1143
    addr.email[485] = (char)0;
#line 1143
    addr.email[486] = (char)0;
#line 1143
    addr.email[487] = (char)0;
#line 1143
    addr.email[488] = (char)0;
#line 1143
    addr.email[489] = (char)0;
#line 1143
    addr.email[490] = (char)0;
#line 1143
    addr.email[491] = (char)0;
#line 1143
    addr.email[492] = (char)0;
#line 1143
    addr.email[493] = (char)0;
#line 1143
    addr.email[494] = (char)0;
#line 1143
    addr.email[495] = (char)0;
#line 1143
    addr.email[496] = (char)0;
#line 1143
    addr.email[497] = (char)0;
#line 1143
    addr.email[498] = (char)0;
#line 1143
    addr.email[499] = (char)0;
#line 1143
    addr.email[500] = (char)0;
#line 1143
    addr.email[501] = (char)0;
#line 1143
    addr.email[502] = (char)0;
#line 1143
    addr.email[503] = (char)0;
#line 1143
    addr.email[504] = (char)0;
#line 1143
    addr.email[505] = (char)0;
#line 1143
    addr.email[506] = (char)0;
#line 1143
    addr.email[507] = (char)0;
#line 1143
    addr.email[508] = (char)0;
#line 1143
    addr.email[509] = (char)0;
#line 1143
    addr.email[510] = (char)0;
#line 1143
    addr.email[511] = (char)0;
#line 1144
    (conn->db)->rows[i] = addr;
#line 1142
    i ++;
  }
#line 1146
  return;
}
}
#line 1147 "tr.c"
void Database_set(struct Connection *conn , int id , char const   *name , char const   *email ) 
{ 
  struct Address *addr ;
  char *res ;
  unsigned long tmp ;
  char *tmp___0 ;
  unsigned long tmp___1 ;

  {
#line 1149
  addr = & (conn->db)->rows[id];
#line 1150
  if (addr->set) {
#line 1150
    die("Already set, delete it first");
  }
#line 1151
  addr->set = 1;
#line 1152
  tmp = __builtin_object_size((void *)(addr->name), 1);
#line 1152
  tmp___0 = __builtin___strncpy_chk(addr->name, name, 512UL, tmp);
#line 1152
  res = tmp___0;
#line 1153
  if (! res) {
#line 1153
    die("Name copy failed");
  }
#line 1154
  tmp___1 = __builtin_object_size((void *)(addr->email), 1);
#line 1154
  res = __builtin___strncpy_chk(addr->email, email, 512UL, tmp___1);
#line 1155
  if (! res) {
#line 1155
    die("Email copy failed");
  }
#line 1156
  return;
}
}
#line 1157 "tr.c"
void Database_get(struct Connection *conn , int id ) 
{ 
  struct Address *addr ;

  {
#line 1159
  addr = & (conn->db)->rows[id];
#line 1160
  if (addr->set) {
#line 1161
    Address_print(addr);
  } else {
#line 1163
    die("ID is not set");
  }
#line 1165
  return;
}
}
#line 1166 "tr.c"
void Database_delete(struct Connection *conn , int id ) 
{ 
  struct Address addr ;

  {
#line 1168
  addr.id = id;
#line 1168
  addr.set = 0;
#line 1168
  addr.name[0] = (char)0;
#line 1168
  addr.name[1] = (char)0;
#line 1168
  addr.name[2] = (char)0;
#line 1168
  addr.name[3] = (char)0;
#line 1168
  addr.name[4] = (char)0;
#line 1168
  addr.name[5] = (char)0;
#line 1168
  addr.name[6] = (char)0;
#line 1168
  addr.name[7] = (char)0;
#line 1168
  addr.name[8] = (char)0;
#line 1168
  addr.name[9] = (char)0;
#line 1168
  addr.name[10] = (char)0;
#line 1168
  addr.name[11] = (char)0;
#line 1168
  addr.name[12] = (char)0;
#line 1168
  addr.name[13] = (char)0;
#line 1168
  addr.name[14] = (char)0;
#line 1168
  addr.name[15] = (char)0;
#line 1168
  addr.name[16] = (char)0;
#line 1168
  addr.name[17] = (char)0;
#line 1168
  addr.name[18] = (char)0;
#line 1168
  addr.name[19] = (char)0;
#line 1168
  addr.name[20] = (char)0;
#line 1168
  addr.name[21] = (char)0;
#line 1168
  addr.name[22] = (char)0;
#line 1168
  addr.name[23] = (char)0;
#line 1168
  addr.name[24] = (char)0;
#line 1168
  addr.name[25] = (char)0;
#line 1168
  addr.name[26] = (char)0;
#line 1168
  addr.name[27] = (char)0;
#line 1168
  addr.name[28] = (char)0;
#line 1168
  addr.name[29] = (char)0;
#line 1168
  addr.name[30] = (char)0;
#line 1168
  addr.name[31] = (char)0;
#line 1168
  addr.name[32] = (char)0;
#line 1168
  addr.name[33] = (char)0;
#line 1168
  addr.name[34] = (char)0;
#line 1168
  addr.name[35] = (char)0;
#line 1168
  addr.name[36] = (char)0;
#line 1168
  addr.name[37] = (char)0;
#line 1168
  addr.name[38] = (char)0;
#line 1168
  addr.name[39] = (char)0;
#line 1168
  addr.name[40] = (char)0;
#line 1168
  addr.name[41] = (char)0;
#line 1168
  addr.name[42] = (char)0;
#line 1168
  addr.name[43] = (char)0;
#line 1168
  addr.name[44] = (char)0;
#line 1168
  addr.name[45] = (char)0;
#line 1168
  addr.name[46] = (char)0;
#line 1168
  addr.name[47] = (char)0;
#line 1168
  addr.name[48] = (char)0;
#line 1168
  addr.name[49] = (char)0;
#line 1168
  addr.name[50] = (char)0;
#line 1168
  addr.name[51] = (char)0;
#line 1168
  addr.name[52] = (char)0;
#line 1168
  addr.name[53] = (char)0;
#line 1168
  addr.name[54] = (char)0;
#line 1168
  addr.name[55] = (char)0;
#line 1168
  addr.name[56] = (char)0;
#line 1168
  addr.name[57] = (char)0;
#line 1168
  addr.name[58] = (char)0;
#line 1168
  addr.name[59] = (char)0;
#line 1168
  addr.name[60] = (char)0;
#line 1168
  addr.name[61] = (char)0;
#line 1168
  addr.name[62] = (char)0;
#line 1168
  addr.name[63] = (char)0;
#line 1168
  addr.name[64] = (char)0;
#line 1168
  addr.name[65] = (char)0;
#line 1168
  addr.name[66] = (char)0;
#line 1168
  addr.name[67] = (char)0;
#line 1168
  addr.name[68] = (char)0;
#line 1168
  addr.name[69] = (char)0;
#line 1168
  addr.name[70] = (char)0;
#line 1168
  addr.name[71] = (char)0;
#line 1168
  addr.name[72] = (char)0;
#line 1168
  addr.name[73] = (char)0;
#line 1168
  addr.name[74] = (char)0;
#line 1168
  addr.name[75] = (char)0;
#line 1168
  addr.name[76] = (char)0;
#line 1168
  addr.name[77] = (char)0;
#line 1168
  addr.name[78] = (char)0;
#line 1168
  addr.name[79] = (char)0;
#line 1168
  addr.name[80] = (char)0;
#line 1168
  addr.name[81] = (char)0;
#line 1168
  addr.name[82] = (char)0;
#line 1168
  addr.name[83] = (char)0;
#line 1168
  addr.name[84] = (char)0;
#line 1168
  addr.name[85] = (char)0;
#line 1168
  addr.name[86] = (char)0;
#line 1168
  addr.name[87] = (char)0;
#line 1168
  addr.name[88] = (char)0;
#line 1168
  addr.name[89] = (char)0;
#line 1168
  addr.name[90] = (char)0;
#line 1168
  addr.name[91] = (char)0;
#line 1168
  addr.name[92] = (char)0;
#line 1168
  addr.name[93] = (char)0;
#line 1168
  addr.name[94] = (char)0;
#line 1168
  addr.name[95] = (char)0;
#line 1168
  addr.name[96] = (char)0;
#line 1168
  addr.name[97] = (char)0;
#line 1168
  addr.name[98] = (char)0;
#line 1168
  addr.name[99] = (char)0;
#line 1168
  addr.name[100] = (char)0;
#line 1168
  addr.name[101] = (char)0;
#line 1168
  addr.name[102] = (char)0;
#line 1168
  addr.name[103] = (char)0;
#line 1168
  addr.name[104] = (char)0;
#line 1168
  addr.name[105] = (char)0;
#line 1168
  addr.name[106] = (char)0;
#line 1168
  addr.name[107] = (char)0;
#line 1168
  addr.name[108] = (char)0;
#line 1168
  addr.name[109] = (char)0;
#line 1168
  addr.name[110] = (char)0;
#line 1168
  addr.name[111] = (char)0;
#line 1168
  addr.name[112] = (char)0;
#line 1168
  addr.name[113] = (char)0;
#line 1168
  addr.name[114] = (char)0;
#line 1168
  addr.name[115] = (char)0;
#line 1168
  addr.name[116] = (char)0;
#line 1168
  addr.name[117] = (char)0;
#line 1168
  addr.name[118] = (char)0;
#line 1168
  addr.name[119] = (char)0;
#line 1168
  addr.name[120] = (char)0;
#line 1168
  addr.name[121] = (char)0;
#line 1168
  addr.name[122] = (char)0;
#line 1168
  addr.name[123] = (char)0;
#line 1168
  addr.name[124] = (char)0;
#line 1168
  addr.name[125] = (char)0;
#line 1168
  addr.name[126] = (char)0;
#line 1168
  addr.name[127] = (char)0;
#line 1168
  addr.name[128] = (char)0;
#line 1168
  addr.name[129] = (char)0;
#line 1168
  addr.name[130] = (char)0;
#line 1168
  addr.name[131] = (char)0;
#line 1168
  addr.name[132] = (char)0;
#line 1168
  addr.name[133] = (char)0;
#line 1168
  addr.name[134] = (char)0;
#line 1168
  addr.name[135] = (char)0;
#line 1168
  addr.name[136] = (char)0;
#line 1168
  addr.name[137] = (char)0;
#line 1168
  addr.name[138] = (char)0;
#line 1168
  addr.name[139] = (char)0;
#line 1168
  addr.name[140] = (char)0;
#line 1168
  addr.name[141] = (char)0;
#line 1168
  addr.name[142] = (char)0;
#line 1168
  addr.name[143] = (char)0;
#line 1168
  addr.name[144] = (char)0;
#line 1168
  addr.name[145] = (char)0;
#line 1168
  addr.name[146] = (char)0;
#line 1168
  addr.name[147] = (char)0;
#line 1168
  addr.name[148] = (char)0;
#line 1168
  addr.name[149] = (char)0;
#line 1168
  addr.name[150] = (char)0;
#line 1168
  addr.name[151] = (char)0;
#line 1168
  addr.name[152] = (char)0;
#line 1168
  addr.name[153] = (char)0;
#line 1168
  addr.name[154] = (char)0;
#line 1168
  addr.name[155] = (char)0;
#line 1168
  addr.name[156] = (char)0;
#line 1168
  addr.name[157] = (char)0;
#line 1168
  addr.name[158] = (char)0;
#line 1168
  addr.name[159] = (char)0;
#line 1168
  addr.name[160] = (char)0;
#line 1168
  addr.name[161] = (char)0;
#line 1168
  addr.name[162] = (char)0;
#line 1168
  addr.name[163] = (char)0;
#line 1168
  addr.name[164] = (char)0;
#line 1168
  addr.name[165] = (char)0;
#line 1168
  addr.name[166] = (char)0;
#line 1168
  addr.name[167] = (char)0;
#line 1168
  addr.name[168] = (char)0;
#line 1168
  addr.name[169] = (char)0;
#line 1168
  addr.name[170] = (char)0;
#line 1168
  addr.name[171] = (char)0;
#line 1168
  addr.name[172] = (char)0;
#line 1168
  addr.name[173] = (char)0;
#line 1168
  addr.name[174] = (char)0;
#line 1168
  addr.name[175] = (char)0;
#line 1168
  addr.name[176] = (char)0;
#line 1168
  addr.name[177] = (char)0;
#line 1168
  addr.name[178] = (char)0;
#line 1168
  addr.name[179] = (char)0;
#line 1168
  addr.name[180] = (char)0;
#line 1168
  addr.name[181] = (char)0;
#line 1168
  addr.name[182] = (char)0;
#line 1168
  addr.name[183] = (char)0;
#line 1168
  addr.name[184] = (char)0;
#line 1168
  addr.name[185] = (char)0;
#line 1168
  addr.name[186] = (char)0;
#line 1168
  addr.name[187] = (char)0;
#line 1168
  addr.name[188] = (char)0;
#line 1168
  addr.name[189] = (char)0;
#line 1168
  addr.name[190] = (char)0;
#line 1168
  addr.name[191] = (char)0;
#line 1168
  addr.name[192] = (char)0;
#line 1168
  addr.name[193] = (char)0;
#line 1168
  addr.name[194] = (char)0;
#line 1168
  addr.name[195] = (char)0;
#line 1168
  addr.name[196] = (char)0;
#line 1168
  addr.name[197] = (char)0;
#line 1168
  addr.name[198] = (char)0;
#line 1168
  addr.name[199] = (char)0;
#line 1168
  addr.name[200] = (char)0;
#line 1168
  addr.name[201] = (char)0;
#line 1168
  addr.name[202] = (char)0;
#line 1168
  addr.name[203] = (char)0;
#line 1168
  addr.name[204] = (char)0;
#line 1168
  addr.name[205] = (char)0;
#line 1168
  addr.name[206] = (char)0;
#line 1168
  addr.name[207] = (char)0;
#line 1168
  addr.name[208] = (char)0;
#line 1168
  addr.name[209] = (char)0;
#line 1168
  addr.name[210] = (char)0;
#line 1168
  addr.name[211] = (char)0;
#line 1168
  addr.name[212] = (char)0;
#line 1168
  addr.name[213] = (char)0;
#line 1168
  addr.name[214] = (char)0;
#line 1168
  addr.name[215] = (char)0;
#line 1168
  addr.name[216] = (char)0;
#line 1168
  addr.name[217] = (char)0;
#line 1168
  addr.name[218] = (char)0;
#line 1168
  addr.name[219] = (char)0;
#line 1168
  addr.name[220] = (char)0;
#line 1168
  addr.name[221] = (char)0;
#line 1168
  addr.name[222] = (char)0;
#line 1168
  addr.name[223] = (char)0;
#line 1168
  addr.name[224] = (char)0;
#line 1168
  addr.name[225] = (char)0;
#line 1168
  addr.name[226] = (char)0;
#line 1168
  addr.name[227] = (char)0;
#line 1168
  addr.name[228] = (char)0;
#line 1168
  addr.name[229] = (char)0;
#line 1168
  addr.name[230] = (char)0;
#line 1168
  addr.name[231] = (char)0;
#line 1168
  addr.name[232] = (char)0;
#line 1168
  addr.name[233] = (char)0;
#line 1168
  addr.name[234] = (char)0;
#line 1168
  addr.name[235] = (char)0;
#line 1168
  addr.name[236] = (char)0;
#line 1168
  addr.name[237] = (char)0;
#line 1168
  addr.name[238] = (char)0;
#line 1168
  addr.name[239] = (char)0;
#line 1168
  addr.name[240] = (char)0;
#line 1168
  addr.name[241] = (char)0;
#line 1168
  addr.name[242] = (char)0;
#line 1168
  addr.name[243] = (char)0;
#line 1168
  addr.name[244] = (char)0;
#line 1168
  addr.name[245] = (char)0;
#line 1168
  addr.name[246] = (char)0;
#line 1168
  addr.name[247] = (char)0;
#line 1168
  addr.name[248] = (char)0;
#line 1168
  addr.name[249] = (char)0;
#line 1168
  addr.name[250] = (char)0;
#line 1168
  addr.name[251] = (char)0;
#line 1168
  addr.name[252] = (char)0;
#line 1168
  addr.name[253] = (char)0;
#line 1168
  addr.name[254] = (char)0;
#line 1168
  addr.name[255] = (char)0;
#line 1168
  addr.name[256] = (char)0;
#line 1168
  addr.name[257] = (char)0;
#line 1168
  addr.name[258] = (char)0;
#line 1168
  addr.name[259] = (char)0;
#line 1168
  addr.name[260] = (char)0;
#line 1168
  addr.name[261] = (char)0;
#line 1168
  addr.name[262] = (char)0;
#line 1168
  addr.name[263] = (char)0;
#line 1168
  addr.name[264] = (char)0;
#line 1168
  addr.name[265] = (char)0;
#line 1168
  addr.name[266] = (char)0;
#line 1168
  addr.name[267] = (char)0;
#line 1168
  addr.name[268] = (char)0;
#line 1168
  addr.name[269] = (char)0;
#line 1168
  addr.name[270] = (char)0;
#line 1168
  addr.name[271] = (char)0;
#line 1168
  addr.name[272] = (char)0;
#line 1168
  addr.name[273] = (char)0;
#line 1168
  addr.name[274] = (char)0;
#line 1168
  addr.name[275] = (char)0;
#line 1168
  addr.name[276] = (char)0;
#line 1168
  addr.name[277] = (char)0;
#line 1168
  addr.name[278] = (char)0;
#line 1168
  addr.name[279] = (char)0;
#line 1168
  addr.name[280] = (char)0;
#line 1168
  addr.name[281] = (char)0;
#line 1168
  addr.name[282] = (char)0;
#line 1168
  addr.name[283] = (char)0;
#line 1168
  addr.name[284] = (char)0;
#line 1168
  addr.name[285] = (char)0;
#line 1168
  addr.name[286] = (char)0;
#line 1168
  addr.name[287] = (char)0;
#line 1168
  addr.name[288] = (char)0;
#line 1168
  addr.name[289] = (char)0;
#line 1168
  addr.name[290] = (char)0;
#line 1168
  addr.name[291] = (char)0;
#line 1168
  addr.name[292] = (char)0;
#line 1168
  addr.name[293] = (char)0;
#line 1168
  addr.name[294] = (char)0;
#line 1168
  addr.name[295] = (char)0;
#line 1168
  addr.name[296] = (char)0;
#line 1168
  addr.name[297] = (char)0;
#line 1168
  addr.name[298] = (char)0;
#line 1168
  addr.name[299] = (char)0;
#line 1168
  addr.name[300] = (char)0;
#line 1168
  addr.name[301] = (char)0;
#line 1168
  addr.name[302] = (char)0;
#line 1168
  addr.name[303] = (char)0;
#line 1168
  addr.name[304] = (char)0;
#line 1168
  addr.name[305] = (char)0;
#line 1168
  addr.name[306] = (char)0;
#line 1168
  addr.name[307] = (char)0;
#line 1168
  addr.name[308] = (char)0;
#line 1168
  addr.name[309] = (char)0;
#line 1168
  addr.name[310] = (char)0;
#line 1168
  addr.name[311] = (char)0;
#line 1168
  addr.name[312] = (char)0;
#line 1168
  addr.name[313] = (char)0;
#line 1168
  addr.name[314] = (char)0;
#line 1168
  addr.name[315] = (char)0;
#line 1168
  addr.name[316] = (char)0;
#line 1168
  addr.name[317] = (char)0;
#line 1168
  addr.name[318] = (char)0;
#line 1168
  addr.name[319] = (char)0;
#line 1168
  addr.name[320] = (char)0;
#line 1168
  addr.name[321] = (char)0;
#line 1168
  addr.name[322] = (char)0;
#line 1168
  addr.name[323] = (char)0;
#line 1168
  addr.name[324] = (char)0;
#line 1168
  addr.name[325] = (char)0;
#line 1168
  addr.name[326] = (char)0;
#line 1168
  addr.name[327] = (char)0;
#line 1168
  addr.name[328] = (char)0;
#line 1168
  addr.name[329] = (char)0;
#line 1168
  addr.name[330] = (char)0;
#line 1168
  addr.name[331] = (char)0;
#line 1168
  addr.name[332] = (char)0;
#line 1168
  addr.name[333] = (char)0;
#line 1168
  addr.name[334] = (char)0;
#line 1168
  addr.name[335] = (char)0;
#line 1168
  addr.name[336] = (char)0;
#line 1168
  addr.name[337] = (char)0;
#line 1168
  addr.name[338] = (char)0;
#line 1168
  addr.name[339] = (char)0;
#line 1168
  addr.name[340] = (char)0;
#line 1168
  addr.name[341] = (char)0;
#line 1168
  addr.name[342] = (char)0;
#line 1168
  addr.name[343] = (char)0;
#line 1168
  addr.name[344] = (char)0;
#line 1168
  addr.name[345] = (char)0;
#line 1168
  addr.name[346] = (char)0;
#line 1168
  addr.name[347] = (char)0;
#line 1168
  addr.name[348] = (char)0;
#line 1168
  addr.name[349] = (char)0;
#line 1168
  addr.name[350] = (char)0;
#line 1168
  addr.name[351] = (char)0;
#line 1168
  addr.name[352] = (char)0;
#line 1168
  addr.name[353] = (char)0;
#line 1168
  addr.name[354] = (char)0;
#line 1168
  addr.name[355] = (char)0;
#line 1168
  addr.name[356] = (char)0;
#line 1168
  addr.name[357] = (char)0;
#line 1168
  addr.name[358] = (char)0;
#line 1168
  addr.name[359] = (char)0;
#line 1168
  addr.name[360] = (char)0;
#line 1168
  addr.name[361] = (char)0;
#line 1168
  addr.name[362] = (char)0;
#line 1168
  addr.name[363] = (char)0;
#line 1168
  addr.name[364] = (char)0;
#line 1168
  addr.name[365] = (char)0;
#line 1168
  addr.name[366] = (char)0;
#line 1168
  addr.name[367] = (char)0;
#line 1168
  addr.name[368] = (char)0;
#line 1168
  addr.name[369] = (char)0;
#line 1168
  addr.name[370] = (char)0;
#line 1168
  addr.name[371] = (char)0;
#line 1168
  addr.name[372] = (char)0;
#line 1168
  addr.name[373] = (char)0;
#line 1168
  addr.name[374] = (char)0;
#line 1168
  addr.name[375] = (char)0;
#line 1168
  addr.name[376] = (char)0;
#line 1168
  addr.name[377] = (char)0;
#line 1168
  addr.name[378] = (char)0;
#line 1168
  addr.name[379] = (char)0;
#line 1168
  addr.name[380] = (char)0;
#line 1168
  addr.name[381] = (char)0;
#line 1168
  addr.name[382] = (char)0;
#line 1168
  addr.name[383] = (char)0;
#line 1168
  addr.name[384] = (char)0;
#line 1168
  addr.name[385] = (char)0;
#line 1168
  addr.name[386] = (char)0;
#line 1168
  addr.name[387] = (char)0;
#line 1168
  addr.name[388] = (char)0;
#line 1168
  addr.name[389] = (char)0;
#line 1168
  addr.name[390] = (char)0;
#line 1168
  addr.name[391] = (char)0;
#line 1168
  addr.name[392] = (char)0;
#line 1168
  addr.name[393] = (char)0;
#line 1168
  addr.name[394] = (char)0;
#line 1168
  addr.name[395] = (char)0;
#line 1168
  addr.name[396] = (char)0;
#line 1168
  addr.name[397] = (char)0;
#line 1168
  addr.name[398] = (char)0;
#line 1168
  addr.name[399] = (char)0;
#line 1168
  addr.name[400] = (char)0;
#line 1168
  addr.name[401] = (char)0;
#line 1168
  addr.name[402] = (char)0;
#line 1168
  addr.name[403] = (char)0;
#line 1168
  addr.name[404] = (char)0;
#line 1168
  addr.name[405] = (char)0;
#line 1168
  addr.name[406] = (char)0;
#line 1168
  addr.name[407] = (char)0;
#line 1168
  addr.name[408] = (char)0;
#line 1168
  addr.name[409] = (char)0;
#line 1168
  addr.name[410] = (char)0;
#line 1168
  addr.name[411] = (char)0;
#line 1168
  addr.name[412] = (char)0;
#line 1168
  addr.name[413] = (char)0;
#line 1168
  addr.name[414] = (char)0;
#line 1168
  addr.name[415] = (char)0;
#line 1168
  addr.name[416] = (char)0;
#line 1168
  addr.name[417] = (char)0;
#line 1168
  addr.name[418] = (char)0;
#line 1168
  addr.name[419] = (char)0;
#line 1168
  addr.name[420] = (char)0;
#line 1168
  addr.name[421] = (char)0;
#line 1168
  addr.name[422] = (char)0;
#line 1168
  addr.name[423] = (char)0;
#line 1168
  addr.name[424] = (char)0;
#line 1168
  addr.name[425] = (char)0;
#line 1168
  addr.name[426] = (char)0;
#line 1168
  addr.name[427] = (char)0;
#line 1168
  addr.name[428] = (char)0;
#line 1168
  addr.name[429] = (char)0;
#line 1168
  addr.name[430] = (char)0;
#line 1168
  addr.name[431] = (char)0;
#line 1168
  addr.name[432] = (char)0;
#line 1168
  addr.name[433] = (char)0;
#line 1168
  addr.name[434] = (char)0;
#line 1168
  addr.name[435] = (char)0;
#line 1168
  addr.name[436] = (char)0;
#line 1168
  addr.name[437] = (char)0;
#line 1168
  addr.name[438] = (char)0;
#line 1168
  addr.name[439] = (char)0;
#line 1168
  addr.name[440] = (char)0;
#line 1168
  addr.name[441] = (char)0;
#line 1168
  addr.name[442] = (char)0;
#line 1168
  addr.name[443] = (char)0;
#line 1168
  addr.name[444] = (char)0;
#line 1168
  addr.name[445] = (char)0;
#line 1168
  addr.name[446] = (char)0;
#line 1168
  addr.name[447] = (char)0;
#line 1168
  addr.name[448] = (char)0;
#line 1168
  addr.name[449] = (char)0;
#line 1168
  addr.name[450] = (char)0;
#line 1168
  addr.name[451] = (char)0;
#line 1168
  addr.name[452] = (char)0;
#line 1168
  addr.name[453] = (char)0;
#line 1168
  addr.name[454] = (char)0;
#line 1168
  addr.name[455] = (char)0;
#line 1168
  addr.name[456] = (char)0;
#line 1168
  addr.name[457] = (char)0;
#line 1168
  addr.name[458] = (char)0;
#line 1168
  addr.name[459] = (char)0;
#line 1168
  addr.name[460] = (char)0;
#line 1168
  addr.name[461] = (char)0;
#line 1168
  addr.name[462] = (char)0;
#line 1168
  addr.name[463] = (char)0;
#line 1168
  addr.name[464] = (char)0;
#line 1168
  addr.name[465] = (char)0;
#line 1168
  addr.name[466] = (char)0;
#line 1168
  addr.name[467] = (char)0;
#line 1168
  addr.name[468] = (char)0;
#line 1168
  addr.name[469] = (char)0;
#line 1168
  addr.name[470] = (char)0;
#line 1168
  addr.name[471] = (char)0;
#line 1168
  addr.name[472] = (char)0;
#line 1168
  addr.name[473] = (char)0;
#line 1168
  addr.name[474] = (char)0;
#line 1168
  addr.name[475] = (char)0;
#line 1168
  addr.name[476] = (char)0;
#line 1168
  addr.name[477] = (char)0;
#line 1168
  addr.name[478] = (char)0;
#line 1168
  addr.name[479] = (char)0;
#line 1168
  addr.name[480] = (char)0;
#line 1168
  addr.name[481] = (char)0;
#line 1168
  addr.name[482] = (char)0;
#line 1168
  addr.name[483] = (char)0;
#line 1168
  addr.name[484] = (char)0;
#line 1168
  addr.name[485] = (char)0;
#line 1168
  addr.name[486] = (char)0;
#line 1168
  addr.name[487] = (char)0;
#line 1168
  addr.name[488] = (char)0;
#line 1168
  addr.name[489] = (char)0;
#line 1168
  addr.name[490] = (char)0;
#line 1168
  addr.name[491] = (char)0;
#line 1168
  addr.name[492] = (char)0;
#line 1168
  addr.name[493] = (char)0;
#line 1168
  addr.name[494] = (char)0;
#line 1168
  addr.name[495] = (char)0;
#line 1168
  addr.name[496] = (char)0;
#line 1168
  addr.name[497] = (char)0;
#line 1168
  addr.name[498] = (char)0;
#line 1168
  addr.name[499] = (char)0;
#line 1168
  addr.name[500] = (char)0;
#line 1168
  addr.name[501] = (char)0;
#line 1168
  addr.name[502] = (char)0;
#line 1168
  addr.name[503] = (char)0;
#line 1168
  addr.name[504] = (char)0;
#line 1168
  addr.name[505] = (char)0;
#line 1168
  addr.name[506] = (char)0;
#line 1168
  addr.name[507] = (char)0;
#line 1168
  addr.name[508] = (char)0;
#line 1168
  addr.name[509] = (char)0;
#line 1168
  addr.name[510] = (char)0;
#line 1168
  addr.name[511] = (char)0;
#line 1168
  addr.email[0] = (char)0;
#line 1168
  addr.email[1] = (char)0;
#line 1168
  addr.email[2] = (char)0;
#line 1168
  addr.email[3] = (char)0;
#line 1168
  addr.email[4] = (char)0;
#line 1168
  addr.email[5] = (char)0;
#line 1168
  addr.email[6] = (char)0;
#line 1168
  addr.email[7] = (char)0;
#line 1168
  addr.email[8] = (char)0;
#line 1168
  addr.email[9] = (char)0;
#line 1168
  addr.email[10] = (char)0;
#line 1168
  addr.email[11] = (char)0;
#line 1168
  addr.email[12] = (char)0;
#line 1168
  addr.email[13] = (char)0;
#line 1168
  addr.email[14] = (char)0;
#line 1168
  addr.email[15] = (char)0;
#line 1168
  addr.email[16] = (char)0;
#line 1168
  addr.email[17] = (char)0;
#line 1168
  addr.email[18] = (char)0;
#line 1168
  addr.email[19] = (char)0;
#line 1168
  addr.email[20] = (char)0;
#line 1168
  addr.email[21] = (char)0;
#line 1168
  addr.email[22] = (char)0;
#line 1168
  addr.email[23] = (char)0;
#line 1168
  addr.email[24] = (char)0;
#line 1168
  addr.email[25] = (char)0;
#line 1168
  addr.email[26] = (char)0;
#line 1168
  addr.email[27] = (char)0;
#line 1168
  addr.email[28] = (char)0;
#line 1168
  addr.email[29] = (char)0;
#line 1168
  addr.email[30] = (char)0;
#line 1168
  addr.email[31] = (char)0;
#line 1168
  addr.email[32] = (char)0;
#line 1168
  addr.email[33] = (char)0;
#line 1168
  addr.email[34] = (char)0;
#line 1168
  addr.email[35] = (char)0;
#line 1168
  addr.email[36] = (char)0;
#line 1168
  addr.email[37] = (char)0;
#line 1168
  addr.email[38] = (char)0;
#line 1168
  addr.email[39] = (char)0;
#line 1168
  addr.email[40] = (char)0;
#line 1168
  addr.email[41] = (char)0;
#line 1168
  addr.email[42] = (char)0;
#line 1168
  addr.email[43] = (char)0;
#line 1168
  addr.email[44] = (char)0;
#line 1168
  addr.email[45] = (char)0;
#line 1168
  addr.email[46] = (char)0;
#line 1168
  addr.email[47] = (char)0;
#line 1168
  addr.email[48] = (char)0;
#line 1168
  addr.email[49] = (char)0;
#line 1168
  addr.email[50] = (char)0;
#line 1168
  addr.email[51] = (char)0;
#line 1168
  addr.email[52] = (char)0;
#line 1168
  addr.email[53] = (char)0;
#line 1168
  addr.email[54] = (char)0;
#line 1168
  addr.email[55] = (char)0;
#line 1168
  addr.email[56] = (char)0;
#line 1168
  addr.email[57] = (char)0;
#line 1168
  addr.email[58] = (char)0;
#line 1168
  addr.email[59] = (char)0;
#line 1168
  addr.email[60] = (char)0;
#line 1168
  addr.email[61] = (char)0;
#line 1168
  addr.email[62] = (char)0;
#line 1168
  addr.email[63] = (char)0;
#line 1168
  addr.email[64] = (char)0;
#line 1168
  addr.email[65] = (char)0;
#line 1168
  addr.email[66] = (char)0;
#line 1168
  addr.email[67] = (char)0;
#line 1168
  addr.email[68] = (char)0;
#line 1168
  addr.email[69] = (char)0;
#line 1168
  addr.email[70] = (char)0;
#line 1168
  addr.email[71] = (char)0;
#line 1168
  addr.email[72] = (char)0;
#line 1168
  addr.email[73] = (char)0;
#line 1168
  addr.email[74] = (char)0;
#line 1168
  addr.email[75] = (char)0;
#line 1168
  addr.email[76] = (char)0;
#line 1168
  addr.email[77] = (char)0;
#line 1168
  addr.email[78] = (char)0;
#line 1168
  addr.email[79] = (char)0;
#line 1168
  addr.email[80] = (char)0;
#line 1168
  addr.email[81] = (char)0;
#line 1168
  addr.email[82] = (char)0;
#line 1168
  addr.email[83] = (char)0;
#line 1168
  addr.email[84] = (char)0;
#line 1168
  addr.email[85] = (char)0;
#line 1168
  addr.email[86] = (char)0;
#line 1168
  addr.email[87] = (char)0;
#line 1168
  addr.email[88] = (char)0;
#line 1168
  addr.email[89] = (char)0;
#line 1168
  addr.email[90] = (char)0;
#line 1168
  addr.email[91] = (char)0;
#line 1168
  addr.email[92] = (char)0;
#line 1168
  addr.email[93] = (char)0;
#line 1168
  addr.email[94] = (char)0;
#line 1168
  addr.email[95] = (char)0;
#line 1168
  addr.email[96] = (char)0;
#line 1168
  addr.email[97] = (char)0;
#line 1168
  addr.email[98] = (char)0;
#line 1168
  addr.email[99] = (char)0;
#line 1168
  addr.email[100] = (char)0;
#line 1168
  addr.email[101] = (char)0;
#line 1168
  addr.email[102] = (char)0;
#line 1168
  addr.email[103] = (char)0;
#line 1168
  addr.email[104] = (char)0;
#line 1168
  addr.email[105] = (char)0;
#line 1168
  addr.email[106] = (char)0;
#line 1168
  addr.email[107] = (char)0;
#line 1168
  addr.email[108] = (char)0;
#line 1168
  addr.email[109] = (char)0;
#line 1168
  addr.email[110] = (char)0;
#line 1168
  addr.email[111] = (char)0;
#line 1168
  addr.email[112] = (char)0;
#line 1168
  addr.email[113] = (char)0;
#line 1168
  addr.email[114] = (char)0;
#line 1168
  addr.email[115] = (char)0;
#line 1168
  addr.email[116] = (char)0;
#line 1168
  addr.email[117] = (char)0;
#line 1168
  addr.email[118] = (char)0;
#line 1168
  addr.email[119] = (char)0;
#line 1168
  addr.email[120] = (char)0;
#line 1168
  addr.email[121] = (char)0;
#line 1168
  addr.email[122] = (char)0;
#line 1168
  addr.email[123] = (char)0;
#line 1168
  addr.email[124] = (char)0;
#line 1168
  addr.email[125] = (char)0;
#line 1168
  addr.email[126] = (char)0;
#line 1168
  addr.email[127] = (char)0;
#line 1168
  addr.email[128] = (char)0;
#line 1168
  addr.email[129] = (char)0;
#line 1168
  addr.email[130] = (char)0;
#line 1168
  addr.email[131] = (char)0;
#line 1168
  addr.email[132] = (char)0;
#line 1168
  addr.email[133] = (char)0;
#line 1168
  addr.email[134] = (char)0;
#line 1168
  addr.email[135] = (char)0;
#line 1168
  addr.email[136] = (char)0;
#line 1168
  addr.email[137] = (char)0;
#line 1168
  addr.email[138] = (char)0;
#line 1168
  addr.email[139] = (char)0;
#line 1168
  addr.email[140] = (char)0;
#line 1168
  addr.email[141] = (char)0;
#line 1168
  addr.email[142] = (char)0;
#line 1168
  addr.email[143] = (char)0;
#line 1168
  addr.email[144] = (char)0;
#line 1168
  addr.email[145] = (char)0;
#line 1168
  addr.email[146] = (char)0;
#line 1168
  addr.email[147] = (char)0;
#line 1168
  addr.email[148] = (char)0;
#line 1168
  addr.email[149] = (char)0;
#line 1168
  addr.email[150] = (char)0;
#line 1168
  addr.email[151] = (char)0;
#line 1168
  addr.email[152] = (char)0;
#line 1168
  addr.email[153] = (char)0;
#line 1168
  addr.email[154] = (char)0;
#line 1168
  addr.email[155] = (char)0;
#line 1168
  addr.email[156] = (char)0;
#line 1168
  addr.email[157] = (char)0;
#line 1168
  addr.email[158] = (char)0;
#line 1168
  addr.email[159] = (char)0;
#line 1168
  addr.email[160] = (char)0;
#line 1168
  addr.email[161] = (char)0;
#line 1168
  addr.email[162] = (char)0;
#line 1168
  addr.email[163] = (char)0;
#line 1168
  addr.email[164] = (char)0;
#line 1168
  addr.email[165] = (char)0;
#line 1168
  addr.email[166] = (char)0;
#line 1168
  addr.email[167] = (char)0;
#line 1168
  addr.email[168] = (char)0;
#line 1168
  addr.email[169] = (char)0;
#line 1168
  addr.email[170] = (char)0;
#line 1168
  addr.email[171] = (char)0;
#line 1168
  addr.email[172] = (char)0;
#line 1168
  addr.email[173] = (char)0;
#line 1168
  addr.email[174] = (char)0;
#line 1168
  addr.email[175] = (char)0;
#line 1168
  addr.email[176] = (char)0;
#line 1168
  addr.email[177] = (char)0;
#line 1168
  addr.email[178] = (char)0;
#line 1168
  addr.email[179] = (char)0;
#line 1168
  addr.email[180] = (char)0;
#line 1168
  addr.email[181] = (char)0;
#line 1168
  addr.email[182] = (char)0;
#line 1168
  addr.email[183] = (char)0;
#line 1168
  addr.email[184] = (char)0;
#line 1168
  addr.email[185] = (char)0;
#line 1168
  addr.email[186] = (char)0;
#line 1168
  addr.email[187] = (char)0;
#line 1168
  addr.email[188] = (char)0;
#line 1168
  addr.email[189] = (char)0;
#line 1168
  addr.email[190] = (char)0;
#line 1168
  addr.email[191] = (char)0;
#line 1168
  addr.email[192] = (char)0;
#line 1168
  addr.email[193] = (char)0;
#line 1168
  addr.email[194] = (char)0;
#line 1168
  addr.email[195] = (char)0;
#line 1168
  addr.email[196] = (char)0;
#line 1168
  addr.email[197] = (char)0;
#line 1168
  addr.email[198] = (char)0;
#line 1168
  addr.email[199] = (char)0;
#line 1168
  addr.email[200] = (char)0;
#line 1168
  addr.email[201] = (char)0;
#line 1168
  addr.email[202] = (char)0;
#line 1168
  addr.email[203] = (char)0;
#line 1168
  addr.email[204] = (char)0;
#line 1168
  addr.email[205] = (char)0;
#line 1168
  addr.email[206] = (char)0;
#line 1168
  addr.email[207] = (char)0;
#line 1168
  addr.email[208] = (char)0;
#line 1168
  addr.email[209] = (char)0;
#line 1168
  addr.email[210] = (char)0;
#line 1168
  addr.email[211] = (char)0;
#line 1168
  addr.email[212] = (char)0;
#line 1168
  addr.email[213] = (char)0;
#line 1168
  addr.email[214] = (char)0;
#line 1168
  addr.email[215] = (char)0;
#line 1168
  addr.email[216] = (char)0;
#line 1168
  addr.email[217] = (char)0;
#line 1168
  addr.email[218] = (char)0;
#line 1168
  addr.email[219] = (char)0;
#line 1168
  addr.email[220] = (char)0;
#line 1168
  addr.email[221] = (char)0;
#line 1168
  addr.email[222] = (char)0;
#line 1168
  addr.email[223] = (char)0;
#line 1168
  addr.email[224] = (char)0;
#line 1168
  addr.email[225] = (char)0;
#line 1168
  addr.email[226] = (char)0;
#line 1168
  addr.email[227] = (char)0;
#line 1168
  addr.email[228] = (char)0;
#line 1168
  addr.email[229] = (char)0;
#line 1168
  addr.email[230] = (char)0;
#line 1168
  addr.email[231] = (char)0;
#line 1168
  addr.email[232] = (char)0;
#line 1168
  addr.email[233] = (char)0;
#line 1168
  addr.email[234] = (char)0;
#line 1168
  addr.email[235] = (char)0;
#line 1168
  addr.email[236] = (char)0;
#line 1168
  addr.email[237] = (char)0;
#line 1168
  addr.email[238] = (char)0;
#line 1168
  addr.email[239] = (char)0;
#line 1168
  addr.email[240] = (char)0;
#line 1168
  addr.email[241] = (char)0;
#line 1168
  addr.email[242] = (char)0;
#line 1168
  addr.email[243] = (char)0;
#line 1168
  addr.email[244] = (char)0;
#line 1168
  addr.email[245] = (char)0;
#line 1168
  addr.email[246] = (char)0;
#line 1168
  addr.email[247] = (char)0;
#line 1168
  addr.email[248] = (char)0;
#line 1168
  addr.email[249] = (char)0;
#line 1168
  addr.email[250] = (char)0;
#line 1168
  addr.email[251] = (char)0;
#line 1168
  addr.email[252] = (char)0;
#line 1168
  addr.email[253] = (char)0;
#line 1168
  addr.email[254] = (char)0;
#line 1168
  addr.email[255] = (char)0;
#line 1168
  addr.email[256] = (char)0;
#line 1168
  addr.email[257] = (char)0;
#line 1168
  addr.email[258] = (char)0;
#line 1168
  addr.email[259] = (char)0;
#line 1168
  addr.email[260] = (char)0;
#line 1168
  addr.email[261] = (char)0;
#line 1168
  addr.email[262] = (char)0;
#line 1168
  addr.email[263] = (char)0;
#line 1168
  addr.email[264] = (char)0;
#line 1168
  addr.email[265] = (char)0;
#line 1168
  addr.email[266] = (char)0;
#line 1168
  addr.email[267] = (char)0;
#line 1168
  addr.email[268] = (char)0;
#line 1168
  addr.email[269] = (char)0;
#line 1168
  addr.email[270] = (char)0;
#line 1168
  addr.email[271] = (char)0;
#line 1168
  addr.email[272] = (char)0;
#line 1168
  addr.email[273] = (char)0;
#line 1168
  addr.email[274] = (char)0;
#line 1168
  addr.email[275] = (char)0;
#line 1168
  addr.email[276] = (char)0;
#line 1168
  addr.email[277] = (char)0;
#line 1168
  addr.email[278] = (char)0;
#line 1168
  addr.email[279] = (char)0;
#line 1168
  addr.email[280] = (char)0;
#line 1168
  addr.email[281] = (char)0;
#line 1168
  addr.email[282] = (char)0;
#line 1168
  addr.email[283] = (char)0;
#line 1168
  addr.email[284] = (char)0;
#line 1168
  addr.email[285] = (char)0;
#line 1168
  addr.email[286] = (char)0;
#line 1168
  addr.email[287] = (char)0;
#line 1168
  addr.email[288] = (char)0;
#line 1168
  addr.email[289] = (char)0;
#line 1168
  addr.email[290] = (char)0;
#line 1168
  addr.email[291] = (char)0;
#line 1168
  addr.email[292] = (char)0;
#line 1168
  addr.email[293] = (char)0;
#line 1168
  addr.email[294] = (char)0;
#line 1168
  addr.email[295] = (char)0;
#line 1168
  addr.email[296] = (char)0;
#line 1168
  addr.email[297] = (char)0;
#line 1168
  addr.email[298] = (char)0;
#line 1168
  addr.email[299] = (char)0;
#line 1168
  addr.email[300] = (char)0;
#line 1168
  addr.email[301] = (char)0;
#line 1168
  addr.email[302] = (char)0;
#line 1168
  addr.email[303] = (char)0;
#line 1168
  addr.email[304] = (char)0;
#line 1168
  addr.email[305] = (char)0;
#line 1168
  addr.email[306] = (char)0;
#line 1168
  addr.email[307] = (char)0;
#line 1168
  addr.email[308] = (char)0;
#line 1168
  addr.email[309] = (char)0;
#line 1168
  addr.email[310] = (char)0;
#line 1168
  addr.email[311] = (char)0;
#line 1168
  addr.email[312] = (char)0;
#line 1168
  addr.email[313] = (char)0;
#line 1168
  addr.email[314] = (char)0;
#line 1168
  addr.email[315] = (char)0;
#line 1168
  addr.email[316] = (char)0;
#line 1168
  addr.email[317] = (char)0;
#line 1168
  addr.email[318] = (char)0;
#line 1168
  addr.email[319] = (char)0;
#line 1168
  addr.email[320] = (char)0;
#line 1168
  addr.email[321] = (char)0;
#line 1168
  addr.email[322] = (char)0;
#line 1168
  addr.email[323] = (char)0;
#line 1168
  addr.email[324] = (char)0;
#line 1168
  addr.email[325] = (char)0;
#line 1168
  addr.email[326] = (char)0;
#line 1168
  addr.email[327] = (char)0;
#line 1168
  addr.email[328] = (char)0;
#line 1168
  addr.email[329] = (char)0;
#line 1168
  addr.email[330] = (char)0;
#line 1168
  addr.email[331] = (char)0;
#line 1168
  addr.email[332] = (char)0;
#line 1168
  addr.email[333] = (char)0;
#line 1168
  addr.email[334] = (char)0;
#line 1168
  addr.email[335] = (char)0;
#line 1168
  addr.email[336] = (char)0;
#line 1168
  addr.email[337] = (char)0;
#line 1168
  addr.email[338] = (char)0;
#line 1168
  addr.email[339] = (char)0;
#line 1168
  addr.email[340] = (char)0;
#line 1168
  addr.email[341] = (char)0;
#line 1168
  addr.email[342] = (char)0;
#line 1168
  addr.email[343] = (char)0;
#line 1168
  addr.email[344] = (char)0;
#line 1168
  addr.email[345] = (char)0;
#line 1168
  addr.email[346] = (char)0;
#line 1168
  addr.email[347] = (char)0;
#line 1168
  addr.email[348] = (char)0;
#line 1168
  addr.email[349] = (char)0;
#line 1168
  addr.email[350] = (char)0;
#line 1168
  addr.email[351] = (char)0;
#line 1168
  addr.email[352] = (char)0;
#line 1168
  addr.email[353] = (char)0;
#line 1168
  addr.email[354] = (char)0;
#line 1168
  addr.email[355] = (char)0;
#line 1168
  addr.email[356] = (char)0;
#line 1168
  addr.email[357] = (char)0;
#line 1168
  addr.email[358] = (char)0;
#line 1168
  addr.email[359] = (char)0;
#line 1168
  addr.email[360] = (char)0;
#line 1168
  addr.email[361] = (char)0;
#line 1168
  addr.email[362] = (char)0;
#line 1168
  addr.email[363] = (char)0;
#line 1168
  addr.email[364] = (char)0;
#line 1168
  addr.email[365] = (char)0;
#line 1168
  addr.email[366] = (char)0;
#line 1168
  addr.email[367] = (char)0;
#line 1168
  addr.email[368] = (char)0;
#line 1168
  addr.email[369] = (char)0;
#line 1168
  addr.email[370] = (char)0;
#line 1168
  addr.email[371] = (char)0;
#line 1168
  addr.email[372] = (char)0;
#line 1168
  addr.email[373] = (char)0;
#line 1168
  addr.email[374] = (char)0;
#line 1168
  addr.email[375] = (char)0;
#line 1168
  addr.email[376] = (char)0;
#line 1168
  addr.email[377] = (char)0;
#line 1168
  addr.email[378] = (char)0;
#line 1168
  addr.email[379] = (char)0;
#line 1168
  addr.email[380] = (char)0;
#line 1168
  addr.email[381] = (char)0;
#line 1168
  addr.email[382] = (char)0;
#line 1168
  addr.email[383] = (char)0;
#line 1168
  addr.email[384] = (char)0;
#line 1168
  addr.email[385] = (char)0;
#line 1168
  addr.email[386] = (char)0;
#line 1168
  addr.email[387] = (char)0;
#line 1168
  addr.email[388] = (char)0;
#line 1168
  addr.email[389] = (char)0;
#line 1168
  addr.email[390] = (char)0;
#line 1168
  addr.email[391] = (char)0;
#line 1168
  addr.email[392] = (char)0;
#line 1168
  addr.email[393] = (char)0;
#line 1168
  addr.email[394] = (char)0;
#line 1168
  addr.email[395] = (char)0;
#line 1168
  addr.email[396] = (char)0;
#line 1168
  addr.email[397] = (char)0;
#line 1168
  addr.email[398] = (char)0;
#line 1168
  addr.email[399] = (char)0;
#line 1168
  addr.email[400] = (char)0;
#line 1168
  addr.email[401] = (char)0;
#line 1168
  addr.email[402] = (char)0;
#line 1168
  addr.email[403] = (char)0;
#line 1168
  addr.email[404] = (char)0;
#line 1168
  addr.email[405] = (char)0;
#line 1168
  addr.email[406] = (char)0;
#line 1168
  addr.email[407] = (char)0;
#line 1168
  addr.email[408] = (char)0;
#line 1168
  addr.email[409] = (char)0;
#line 1168
  addr.email[410] = (char)0;
#line 1168
  addr.email[411] = (char)0;
#line 1168
  addr.email[412] = (char)0;
#line 1168
  addr.email[413] = (char)0;
#line 1168
  addr.email[414] = (char)0;
#line 1168
  addr.email[415] = (char)0;
#line 1168
  addr.email[416] = (char)0;
#line 1168
  addr.email[417] = (char)0;
#line 1168
  addr.email[418] = (char)0;
#line 1168
  addr.email[419] = (char)0;
#line 1168
  addr.email[420] = (char)0;
#line 1168
  addr.email[421] = (char)0;
#line 1168
  addr.email[422] = (char)0;
#line 1168
  addr.email[423] = (char)0;
#line 1168
  addr.email[424] = (char)0;
#line 1168
  addr.email[425] = (char)0;
#line 1168
  addr.email[426] = (char)0;
#line 1168
  addr.email[427] = (char)0;
#line 1168
  addr.email[428] = (char)0;
#line 1168
  addr.email[429] = (char)0;
#line 1168
  addr.email[430] = (char)0;
#line 1168
  addr.email[431] = (char)0;
#line 1168
  addr.email[432] = (char)0;
#line 1168
  addr.email[433] = (char)0;
#line 1168
  addr.email[434] = (char)0;
#line 1168
  addr.email[435] = (char)0;
#line 1168
  addr.email[436] = (char)0;
#line 1168
  addr.email[437] = (char)0;
#line 1168
  addr.email[438] = (char)0;
#line 1168
  addr.email[439] = (char)0;
#line 1168
  addr.email[440] = (char)0;
#line 1168
  addr.email[441] = (char)0;
#line 1168
  addr.email[442] = (char)0;
#line 1168
  addr.email[443] = (char)0;
#line 1168
  addr.email[444] = (char)0;
#line 1168
  addr.email[445] = (char)0;
#line 1168
  addr.email[446] = (char)0;
#line 1168
  addr.email[447] = (char)0;
#line 1168
  addr.email[448] = (char)0;
#line 1168
  addr.email[449] = (char)0;
#line 1168
  addr.email[450] = (char)0;
#line 1168
  addr.email[451] = (char)0;
#line 1168
  addr.email[452] = (char)0;
#line 1168
  addr.email[453] = (char)0;
#line 1168
  addr.email[454] = (char)0;
#line 1168
  addr.email[455] = (char)0;
#line 1168
  addr.email[456] = (char)0;
#line 1168
  addr.email[457] = (char)0;
#line 1168
  addr.email[458] = (char)0;
#line 1168
  addr.email[459] = (char)0;
#line 1168
  addr.email[460] = (char)0;
#line 1168
  addr.email[461] = (char)0;
#line 1168
  addr.email[462] = (char)0;
#line 1168
  addr.email[463] = (char)0;
#line 1168
  addr.email[464] = (char)0;
#line 1168
  addr.email[465] = (char)0;
#line 1168
  addr.email[466] = (char)0;
#line 1168
  addr.email[467] = (char)0;
#line 1168
  addr.email[468] = (char)0;
#line 1168
  addr.email[469] = (char)0;
#line 1168
  addr.email[470] = (char)0;
#line 1168
  addr.email[471] = (char)0;
#line 1168
  addr.email[472] = (char)0;
#line 1168
  addr.email[473] = (char)0;
#line 1168
  addr.email[474] = (char)0;
#line 1168
  addr.email[475] = (char)0;
#line 1168
  addr.email[476] = (char)0;
#line 1168
  addr.email[477] = (char)0;
#line 1168
  addr.email[478] = (char)0;
#line 1168
  addr.email[479] = (char)0;
#line 1168
  addr.email[480] = (char)0;
#line 1168
  addr.email[481] = (char)0;
#line 1168
  addr.email[482] = (char)0;
#line 1168
  addr.email[483] = (char)0;
#line 1168
  addr.email[484] = (char)0;
#line 1168
  addr.email[485] = (char)0;
#line 1168
  addr.email[486] = (char)0;
#line 1168
  addr.email[487] = (char)0;
#line 1168
  addr.email[488] = (char)0;
#line 1168
  addr.email[489] = (char)0;
#line 1168
  addr.email[490] = (char)0;
#line 1168
  addr.email[491] = (char)0;
#line 1168
  addr.email[492] = (char)0;
#line 1168
  addr.email[493] = (char)0;
#line 1168
  addr.email[494] = (char)0;
#line 1168
  addr.email[495] = (char)0;
#line 1168
  addr.email[496] = (char)0;
#line 1168
  addr.email[497] = (char)0;
#line 1168
  addr.email[498] = (char)0;
#line 1168
  addr.email[499] = (char)0;
#line 1168
  addr.email[500] = (char)0;
#line 1168
  addr.email[501] = (char)0;
#line 1168
  addr.email[502] = (char)0;
#line 1168
  addr.email[503] = (char)0;
#line 1168
  addr.email[504] = (char)0;
#line 1168
  addr.email[505] = (char)0;
#line 1168
  addr.email[506] = (char)0;
#line 1168
  addr.email[507] = (char)0;
#line 1168
  addr.email[508] = (char)0;
#line 1168
  addr.email[509] = (char)0;
#line 1168
  addr.email[510] = (char)0;
#line 1168
  addr.email[511] = (char)0;
#line 1169
  (conn->db)->rows[id] = addr;
#line 1170
  return;
}
}
#line 1171 "tr.c"
void Database_list(struct Connection *conn ) 
{ 
  int i ;
  struct Database *db ;
  struct Address *cur ;

  {
#line 1173
  i = 0;
#line 1174
  db = conn->db;
#line 1175
  i = 0;
#line 1175
  while (i < 100) {
#line 1176
    cur = & db->rows[i];
#line 1177
    if (cur->set) {
#line 1178
      Address_print(cur);
    }
#line 1175
    i ++;
  }
#line 1181
  return;
}
}
#line 1182 "tr.c"
int main(int argc , char **argv ) 
{ 
  char *filename ;
  char action ;
  struct Connection *conn ;
  struct Connection *tmp ;
  int id ;

  {
#line 1184
  if (argc < 3) {
#line 1184
    die("USAGE: ex17 <dbfile> <action> [action params]");
  }
#line 1185
  filename = *(argv + 1);
#line 1186
  action = *(*(argv + 2) + 0);
#line 1187
  tmp = Database_open((char const   *)filename, action);
#line 1187
  conn = tmp;
#line 1188
  id = 0;
#line 1189
  if (argc > 3) {
#line 1189
    id = atoi((char const   *)*(argv + 3));
  }
#line 1190
  if (id >= 100) {
#line 1190
    die("There\'s not that many records.");
  }
#line 1191
  switch ((int )action) {
  case 99: 
#line 1193
  Database_create(conn);
#line 1194
  Database_write(conn);
#line 1195
  break;
  case 103: 
#line 1197
  if (argc != 4) {
#line 1197
    die("Need an id to get");
  }
#line 1198
  Database_get(conn, id);
#line 1199
  break;
  case 115: 
#line 1201
  if (argc != 6) {
#line 1201
    die("Need id, name, email to set");
  }
#line 1202
  Database_set(conn, id, (char const   *)*(argv + 4), (char const   *)*(argv + 5));
#line 1203
  Database_write(conn);
#line 1204
  break;
  case 100: 
#line 1206
  if (argc != 4) {
#line 1206
    die("Need id to delete");
  }
#line 1207
  Database_delete(conn, id);
#line 1208
  Database_write(conn);
#line 1209
  break;
  case 108: 
#line 1211
  Database_list(conn);
#line 1212
  break;
  default: 
#line 1214
  die("Invalid action, only: c=create, g=get, s=set, d=del, l=list");
  }
#line 1216
  Database_close(conn);
#line 1217
  return (0);
}
}
